### ISSUE TITLE
save -> last recent folderlist opens -> up-arrow

### ISSUE THREAD

**Issue by rmmbr** [opto/nostalgy-xpi#10]
I focus one mail, I press 's', the last recent folderlist opens and I press the up-arrow-key.

=> nothing happens

assumed => with every press of the up-arrow button I step one entry up in the list

**Comment by rmmbr** [comment]
Sorry I forget my configuration. W10 1909, TB 68.3.0, Nostalgy 0.394.

**Comment by emanueleterracina** [comment]
Yeah would love it too
To be honest it was like that in Nostalgy too, annoying

**Comment by rmmbr** [comment]
> Yeah would love it too
> To be honest it was like that in Nostalgy too, annoying
That's right. My description above is the original behavior of the 'old' nostalgy.

**Comment by rmmbr** [comment]
> To be honest it was like that in Nostalgy too, annoying
@emanueleterracina: That's right. My description above is the behavior of the 'old' nostalgy.

**Comment by rmmbr** [comment]
> To be honest it was like that in Nostalgy too, annoying
@emanueleterracina: That's right. My description above is the behavior of the old nostalgy.

**Comment by rmmbr** [comment]
>To be honest it was like that in Nostalgy too, annoying

@emanueleterracina: That's right. My description above is the behaviour of the 'old' nostalgy.

**Comment by opto** [comment]
yes, that was already broken in TB 60, due to some changes in TB. I tried, but did not yet find a solution to reactivate that.

**Comment by Olifair** [comment]
I have the "statistical predition" option switchend on, and this this option the arrow key worked under TB60 (windows 10). But it does not anymore now

**Comment by opto** [comment]
should be ok now, but see #29 until I have uploaded the fix
