### ISSUE TITLE
after go to folder, allow to 'go back' (= alt g)

### ISSUE THREAD

**Issue by opto** [opto/nostalgy-xpi#107]
just looking for something in a folder? alt g allows to go back to the folder where you came from

**Comment by Olifair** [comment]
Does not seem to work here with Nostalgy 2.3.1 and TB 78.11.0
I have tried going to a folder using G within the same IMPA account or to locals folders : ATL+g just gives no reaction at all.
I can seen the keybinding in the Nostalgy preferences, I have even redone it. No change. 
 A pity, I was looking forward to this.

**Comment by opto** [comment]
maybe the same problem as #111: loaded too early into TB?

Please try the workaround (deactivate addon, then activate) and report whether it works then.
Definitely did work here before upload, but still - every PC could be different.

Thanks,

Klaus

**Comment by Olifair** [comment]
Yes, I tried the workaround, does still not work. I have tried to jump from IMAP inbox to either IMAP or local folders, neither do work. I'm a bit frustrated, as I would found thi immensely usefull. I have actually programme "I" to go back to my Inbox (don't know if I broke any TB functionality with this, but not one that I needed :-)

**Comment by opto** [comment]
I can confirm - something broke versus the version I tested last.
Don't worry, I will look that it gets working again.

Klaus

**Comment by opto** [comment]
workaround: goto TB settings, about:config.
search for all Nostalgy settings. find nostalgy.actions._back
Please delete this (Zurücksetzen in rightclick menu in German TB). At that moment, go back works here.

I still need to find out where this pref comes from, but at least, without the pref, it does go back

**Comment by opto** [comment]
could be caused by second go_back or _back key: please delete that one, see message in #111 and please try v2.3.6

**Comment by opto** [comment]
Please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.1 for TB 78 - TB 91
