### ISSUE TITLE
TB 78.10.2 64 bit cannot scroll rule list

### ISSUE THREAD

**Issue by jmart777** [opto/nostalgy-xpi#108]
When i start Nostalgy it comes up with part of rules list showing but am unable to move or scroll down in list. its just stuck there.

[Document.docx](https://github.com/opto/nostalgy-xpi/files/6544074/Document.docx)

**Comment by opto** [comment]
Please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.1

**Comment by jmart777** [comment]
Excellent !! Working now.  using it with 91.0b1 (64-bit)
One small thing re rules - when moving a rule up or down the page to a new position, would it be possible for the rules pages to automatically scroll up or down so you can always see the position of the one that you are moving. I think it used to be this way.  At the moment you have no idea where the one you are moving has got to as it disappears off the page & you have to manually scroll the page to find it again.
Thanks.

**Comment by jmart777** [comment]
OR   If the "Contains" column was made to sort A-Z  or Z-A  by clicking on column heading, that would do the trick, as I list my rules alphabetically by this column when I manually move them.
Thanks
