### ISSUE TITLE
TB 78.10.2: Uncaught TypeError: manage_emails.WL.messenger.runtime.getURL is not a function

### ISSUE THREAD

**Issue by mguessan** [opto/nostalgy-xpi#109]
Latest Thunderbird update broke this extension again.

shift s no longer works and triggers exception:

`Uncaught TypeError: manage_emails.WL.messenger.runtime.getURL is not a function
    onNostalgyLoad chrome://nostalgy/content/nostalgy.js:293`

**Comment by opto** [comment]
thanks for the info. Which OS?
That is still working on (my) Win 10 pro

**Comment by mguessan** [comment]
On Windows 8 ... I think last update broke it, will check with a Thunderbird portable I have

**Comment by mguessan** [comment]
Update: wrong diagnostic. I thought Nostalgy was broken when it was just a hidden calendar dialog that blocked its commands.

Thus the only here is the above message in TB console that does seem to have any impact on Nostalgy behavior.

**Comment by opto** [comment]
thanks for pointing me to this.
By the way, there is another way to get the extension path (the moz- .. path could be different elsewhere), using ExtensionParent +  some other code I don't remember right now (can look it up and share if you need it).

Klaus

**Comment by opto** [comment]
fixed in newest version, will be uploaded to ATN in the next days

**Comment by opto** [comment]
Please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.1 for TB 78 - TB 91
