### ISSUE TITLE
Nostalgy-xpi prevents display of real web address

### ISSUE THREAD

**Issue by ExpPhysU** [opto/nostalgy-xpi#11]
Hi, thanks for the update for TB>68. I noticed the followin issues:
- nostalgy-debug: the status bar at the bottom disappears from time to time. Otherwise it works as expectet

-nostalgy-xpi: all the right justified items of the staus  bar are moved to the left. The display of the real web address (important for security) is not possible. There is no way  to move things right. On startup there is a text input field, as mentionned somewhere else.
It would be grat if you could make nostalgy-xpi display the web addresses again, when hovering over the link.
Thanks!

**Comment by jpschewe** [comment]
I have noticed this as well. See the attached screenshots. It appears that nostalgy really wants to left justify the status bar items which removes the space to show the web address that is being moused over. I suggest leaving the items right justified or removing the keyboard shortcut information from the status bar. If people read the documentation they shouldn't need the help in the status bar.

![no-nostalgy](https://user-images.githubusercontent.com/226585/70389773-9c32a480-1989-11ea-82bc-dc839ee814a2.png)
![nostalgy](https://user-images.githubusercontent.com/226585/70389774-9c32a480-1989-11ea-98c1-66ed5735994e.png)

**Comment by MLopez-Ibanez** [comment]
Hi @opto,

Please take a look at my fork: https://github.com/MLopez-Ibanez/nostalgy

I have alleviated this issue and removed an obsolete attribute. I have added you as a collaborator.

I don't think neither you nor I have enough time to update nostalgy to WebExtensions, so it will stop working for good for the next Thunderbird release. We need to ask for help and collaborators. Any help pouring over Thunderbird documents, asking in mailing lists and discussion groups, testing various ideas, writing tests, etc would help even if someone cannot program at all.

**Comment by opto** [comment]
I am working on webextensions, but also, TB core team needs to give more ressources for that. There are a few discussions and a meta bug in bugzilla for what is needed.

Klaus

**Comment by rmmbr** [comment]
>  I suggest leaving the items right justified or removing the keyboard shortcut information from the status bar. If people read the documentation they shouldn't need the help in the status bar.

@jpschewe: I agree with you. If there is no chance of showing the url-information of the real web address it's the best to show no information of the shortcuts and use the status bar of TB as it is.

**Comment by MLopez-Ibanez** [comment]
> > I suggest leaving the items right justified or removing the keyboard shortcut information from the status bar. If people read the documentation they shouldn't need the help in the status bar.
> 
> @jpschewe: I agree with you. If there is no chance of showing the url-information of the real web address it's the best to show no information of the shortcuts and use the status bar of TB as it is.

If you know how the element that displays the URL is called, it is easy to change the code here: 

https://github.com/MLopez-Ibanez/nostalgy/blob/bb04bc1e7f2441322aae3c30ec1ec74897bc9fe8/chrome/content/messageOverlay.xul#L43

to insert the nostalgy status label after that element. Perhaps ask in the thunderbird mailing lists for the name?

Another solution would be to set the width of the nostalgy box to a fixed percentage of the total width of the status bar. No idea how to do this. If you ask in the thunderbird mailing lists and find out, I can change it easily. There is this code: https://github.com/MLopez-Ibanez/nostalgy/blob/7929061852f3f664372cf5ef7dbaf7f2e3ce90ac/chrome/content/nostalgy.js#L183

but it doesn't seem to work. Perhaps some Thunderbird developer has a suggestion. Please ask and let us know.

**Comment by opto** [comment]
I have nostalgy nearly finished. As bonus, most likely, it will allow to automatically create new rules.

Please just have a little patience. Once tested, I will submit to addons.thunderbird.net so that everybody can download it from TB 68.

Klaus

**Comment by opto** [comment]
this is now working will upload today
