### ISSUE TITLE
Key bindings in 2.3.1

### ISSUE THREAD

**Issue by snchong** [opto/nostalgy-xpi#110]
As of 2.3.1 (June 11, 2021), the "S" key is triggering Thunderbird's default "Star/Unstar" functionality instead of the Nostalgy++'s move message functionality. 

I appreciate that Nostalgy++ allows the key binding to be changed, but it would be nice if the Nostalgy++ key bindings overrode Thunderbird's built in bindings.

Thank so much for an indispensable add on!

**Comment by tuxayo** [comment]
Try going in the addon manager
- select nostalgy
- wrench icon
- keys
- click for example on the "s" next to "save message"
- it will ask the key, so it's like you will rebind it
- rebind it to "s" again
- go back to inbox and retry the key commands.

I my case it worked

**Comment by tuxayo** [comment]
What are your other addons that could interfere? I have Conversations.

**Comment by snchong** [comment]
Thanks so much @tuxayo! That worked on one of my computers. On the other, it worked after I disabled other extensions (including Coversations).

**Comment by tuxayo** [comment]
Does it work durably or is that necessary for each session? https://github.com/opto/nostalgy-xpi/issues/111#issuecomment-860081157
