### ISSUE TITLE
Events pane disappears on 's' / move mail

### ISSUE THREAD

**Issue by mmeeks** [opto/nostalgy-xpi#114]
I love Nostalgy - it makes T-bird usable.

However in the recent version in a recent T-bird; if I have:

* t-bird using half the screen (say the right half)
* press 's' to move a message, start typing in the search field
* the 'Move messages to' popup arrives at the bottom, and the window often (but not always) re-sizes width-wise.

That chops my (rather vital) 'Events' in the Today Pane out of the app view by forcing a re-size of the window to the right.
Of course without the events view it forces the folder identification out.

I assume that is not deliberate; presuambly it doesn't occur when t-bird is full-screen.

**Comment by DecoDogs** [comment]
I'm using TB 78.8.1, Linux.  I found online a work-around for this problem (it may not be the ultimate 'fix' though):

Edit -> Preferences -> scroll to bottom of General category ->  config editor
search for 'nostalgy' and change 'extensions.nostalgy.FolderBoxChars' to a smaller value (I landed on 35)

I have often several nested levels of folders and sometimes have lengthy names, so sometimes have to scroll the text box horizontally.

**Comment by mmeeks** [comment]
Thanks so much - that's a beautiful workaround =) and yes, lots of nested mail folders here too.

**Comment by DecoDogs** [comment]
Glad to share the knowledge!

(Unfortunately, I have no idea as to how to close an issue here :) )

**Comment by opto** [comment]
I think this resizing came up when the toolbar was changed from an element to a class.
I am thinking of eventually not putting this box into the statusbar but into some box above the statusbar which could give full width to the folderbox.

And yes, i am testing on a notebook in full screen, so I never caught this behaviour.

Klaus

**Comment by mmeeks** [comment]
Either way - thanks for a great plugin that makes T-bird usable =) you rock.

**Comment by opto** [comment]
Please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.1 for TB 78 - TB 91

**Comment by opto** [comment]
does this work for you? You can now set the width of the folderbox in the settings
This version has switched off tab recognition and works in all tabs, does this help? (.. and a new feature ...)

 : https://github.com/opto/nostalgy-xpi/releases/tag/3.0.7.

**Comment by mmeeks** [comment]
Tested the setting there - thanks. It also works for me on first-start where previously I had to disable and re-enable the plugin when starting from a clean start in order to get the keybindings to work - so a big improvement =)
Thanks!
