### ISSUE TITLE
EscapeEscapeEscapeEscape in folderbox

### ISSUE THREAD

**Issue by opto** [opto/nostalgy-xpi#116]
from @chconnor #111:

Side note: I figured out how to trigger "EscapeEscapeEscapeEscape": start TB, hit g, click in the blank space where a message content would be, then hit escape: every time you hit ESC or any other key, it writes the key in the text field.

**Comment by opto** [comment]
not really a bug, a new TB feature? If you click outside of the folderbox then the  focus is outside, we cannot catch the esc (could be part of your foldername). we can only catch esc if cursor is inside folderbox.
Reason: it now does not give the numeric for esc (27?) but puts in esc letters, as you see.

Put mouse back into folderbox - esc - box is gone

**Comment by opto** [comment]
Please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.1 for TB 78 - TB 91

**Comment by chconnor** [comment]
Thanks -- EscapeEscapeEscape is still happening for me... TB 78.11.0, Kubuntu 21.04, Nostalgy 3.0.1
