### ISSUE TITLE
custom shortcuts don't work anymore after latest update

### ISSUE THREAD

**Issue by Il-falco** [opto/nostalgy-xpi#119]
I already deleted some of those and then re-created them but that doesn't seem to change anything. No action happens after entering the saved key strokes.

**Comment by opto** [comment]
thanks for the info.
Which OS, TB version, 32bit or 64 bit TB?

I tested for the Go at the bottom in TB 78 (32 and 64 bit) and 91b1, where it worked on Win10 home

**Comment by opto** [comment]
but multiprocess TB has some strange timing effects, so things could be different with another processor speed

**Comment by Il-falco** [comment]
Thanks and sorry for not including the specs of my system,
Windows 7 SP1 64-bit, TB 78.12.0 32-bit.

I also re-started the computer, but it didn't change anything. 

Also the prefigured keys like "S", "G", don't provoke any action which they did before Nostalgy++ updated last night.

Could you please provide the xpi file for the previous version. I will install that one and de-activate the auto-update for the add-ons for a while.

**Comment by opto** [comment]
you can find various releases here: https://github.com/opto/nostalgy-xpi/releases.
Also, on addons.thunderbird.net, for Nostalgy++, you can get all old releases that were published there: 
https://addons.thunderbird.net/de/thunderbird/addon/nostalgy_ng/versions/

chnage de to en-US in the link to have the English webpage

**Comment by Il-falco** [comment]
Thank you! Much appreciated.
I just went back to 2.3.1 which worked fine on my system. 

After trying back and forth several times your workaround deactivating the addon and then re-activating it, the shortcuts finally worked again. 

But you wrote that it might only be necessary on TB 64-bit. So maybe you would like to modify your explanation and also include TB 32-bit.

Thanks again!

**Comment by opto** [comment]
I would have expected you have a Mac. Why is win 7 different from win 10?
Is your PC exceptionally fast? We do have timing problems which we overcome with a delay, maybe that is too short?

**Comment by Il-falco** [comment]
No, my PC is not exceptionally fast. It's a tried and true Lenovo W520 workstation laptop. I'm much too busy with my actual work in order to buy new stuff every few years and then try to make it work as well and reliably as the system it should replace. That doesn't mean that I'm against real improvements. Quite the opposite to be honest as most engineers I'd guess. But the reality in IT often proves that "never change a running system!" is an absolutely valid advice if you primarily want / need to get stuff done.

**Comment by opto** [comment]
you could try the new version 3.0.5:https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.5

**Comment by opto** [comment]
does this work for you?
This version has switched off tab recognition and works in all tabs, does this help? (.. and a new feature ...)

 : https://github.com/opto/nostalgy-xpi/releases/tag/3.0.7.

**Comment by opto** [comment]
works in 3.0.8- Please reopen issue if still happening for you.

Klaus
