### ISSUE TITLE
Unable to Create New Shortcuts with Update

### ISSUE THREAD

**Issue by HistorianBenj** [opto/nostalgy-xpi#120]
(I'm on a MacBook Air 2018 running OS BigSur 11.4; TBird 78.12.0 - 64-bit; Nostalgy 3.0.4
<img width="1440" alt="Screenshot 2021-07-23 at 13 02 45" src="https://user-images.githubusercontent.com/87864568/126790553-13ce3546-c086-4d1e-95cc-06bae4780874.png">
.)

When I go to Keys, which is the bit of Nostalgy I use (so convenient), I get the attached screen: I can delete a shortcut or change a key for any of those visible; but I don't seem to be able to scroll at all to see the rest of them, or (presumably) the mechanisms for creating new shortcuts at the bottom of the page.  So I can't ever edit or add to my current scheme of shortcut keys.  Is there anything you're able to do?

Nostalgy is wonderful, by the way: many thanks for keeping it going.

**Comment by HistorianBenj** [comment]
An update on #120: it looks as if you may have tried to fix this, for which many thanks.  

Sadly, I still can't scroll down the Nostalgy screen (as above), and am thus unable to create new shortcuts, as that bit is off the bottom of my screen.  Does the Nostalgy screen need a scrolling facility perhaps?

If I view all windows, as here, I can see the full document: so clearly it is there.  But I don't know how to activate that when it's a normal window.  (This may of course be a simple problem at my end, or just my ignorance.)

<img width="1440" alt="Screenshot 2021-07-30 at 16 34 29" src="https://user-images.githubusercontent.com/87864568/127677611-5a71737a-c1d4-4cf1-a12f-43be212742a9.png">

In hope!

**Comment by opto** [comment]
this can scroll on win 10 in TB 91.0b5:
https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.5

**Comment by HistorianBenj** [comment]
It is kind of you to provide this.  Unfortunately I'm on a Mac (MacBook Air 2018 running OS BigSur 11.4; TBird 78.12.0 - 64-bit; Nostalgy 3.0.4), so I don't think I can use this?  I think you said Mac may be a problem.  But I'm also not that tech savvy, so it is possible that I just can't work out how to attach it to my TBird/Nostalgy++.  Any pointers as to how I can do that welcome - and sorry for ignorance.

**Comment by opto** [comment]
maybe this works as well in 3.0.8?
