### ISSUE TITLE
Unable to create new rules

### ISSUE THREAD

**Issue by klausatlas** [opto/nostalgy-xpi#124]
I use Nostalgy 3.0.4 with TB 78.12.0  on OpenSuse 15.3.. Creating new rules doesn't work for me any more. This means I can create a new rule without problems and it appears in the list of rules. However when I close the Nostalgy Preferences window and open it again the rule has disappeared again. Any way to solve this?

**Comment by rpmohn** [comment]
I'm likewise unable to save _any_ changes to Nostalgy. I'm running Nostalgy 3.0.4 with TB 78.11.0 (64-bit) on Ubuntu 20.04.

As an experiment, I was able to close TB, manually edit the `prefs.js` file to change one of the `extensions.nostalgy.` settings from `false` to `true`, and then see that change when I relaunched TB. If I knew the syntax for creating a new save to folder key binding I'd be happy without the GUI. If there were a reference for _all_ the syntax for creating _all_ the nostalgy prefs I'd be happier. If the GUI worked I'd be happiest.

**Comment by klausatlas** [comment]
In fact changing prefs.js I could also add the new rule. But this is rather clumsy.

**Comment by rpmohn** [comment]
@klausatlas do you have a Save-To-Folder keybinding example that you could post here? Something like `Save -> user@example.com/Foo` mapped to `shift M`, for example?

**Comment by klausatlas** [comment]
It seems you need two lines:

user_pref("extensions.nostalgy.actions._0", "Go -> user@example.com/Foo");
user_pref("extensions.nostalgy.keys._0", "I");

_0 starts a counter. "shift M" should work as well

**Comment by rpmohn** [comment]
Very nice, that works great! Thank you, now I am a little bit happier!

**Comment by opto** [comment]
yes, I am sorry. Due to multiprocess, I think, TB loads the keys at the wrong time in the wrong process. And then they are overwritten when you see the main window.

This happens on some PC's, but not all.
We spend more than 12 hours together with a Thunderbird developer to find ways around.
My recent idea is just to delay Nostalgy setup by 1 second or so and see whether that works.

There is also a new version here (still without delays) https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.6

maybe that helps.

Klaus

**Comment by klausatlas** [comment]
I don't think this is the problems. For me the keys and rules are loaded perfectly, but I cannot create new ones. As I said, I can create them but then they are gone immediately. It seems they are never written to prefs.js.

**Comment by opto** [comment]
ah thanks. I actually tested that before uploading.
Which OS, PC type/speed?

I just tested on TB 91, loading the 3.0.6 on win10 pro, and it can create keys.

**Comment by klausatlas** [comment]
OpenSUSE 15.3 on a DELL Lattitude 7480 with 4 cores  Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz using Nostalgy++ 3.0.4

**Comment by klausatlas** [comment]
Thanks for finding this! I upgraded as well and when I expand the rules window I can find the ok button. Sorry for the noise.
