### ISSUE TITLE
Release 3.0.7 prevents selection of "Inbox" (or other folder) after deleting emails in "Deleted" folder

### ISSUE THREAD

**Issue by rogerval** [opto/nostalgy-xpi#126]
After installing release 3.0.7 I happened to need to delete emails here and there, and when I cleared the contents of the "Deleted" folder, and attempted to select the "Inbox" again, the "Deleted" folder remained in the main window. I couldn't select any other folders, either; I had to shut down and re-start Thunderbird to clear the problem.
Reverting to release 3.0.6 has caused Thunderbird to work normally again.
I'm currently using 64 bit Thunderbird version 78.13.0 on Windows 10 21H1 (OS build 19043 .1165) on a Lenovo P310 Thinkstation with 16 GB RAM.
By the way, thanks for all your hard work on Nostalgy, it's greatly appreciated. :-)
If more information is required, I'll happily provide it.
Kind regards, Roger V.

**Comment by opto** [comment]
can you send a copy of error console, when the error occurs?  ctrl-shift-j, all at the same time, or in a submenu of tools.

thanks

**Comment by rogerval** [comment]
Here's a copy of the error console output (only errors shown):

05:15:57.375
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
05:15:57.535
Error while loading 'jar:file:///C:/Program%20Files/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:570
05:15:57.724
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
05:15:58.187
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
05:15:58.389
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
05:15:58.390
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
05:15:58.877
DOMException: CSSStyleSheet.cssRules getter: Can't access rules of still-loading stylsheet tabmail.js:914:21
05:16:47.488
Uncaught 
Exception { name: "NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED", message: "JavaScript component does not have a method named: \"isSelected\"'JavaScript component does not have a method named: \"isSelected\"' when calling method: [nsITreeSelection::isSelected]", result: 2153185328, filename: "chrome://global/content/elements/tree.js", lineNumber: 68, columnNumber: 0, data: null, stack: "MozTreeChildren/<@chrome://global/content/elements/tree.js:68:31\n", location: XPCWrappedNative_NoHelper }
tree.js:68
05:16:47.686
Uncaught 
Exception { name: "NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED", message: "JavaScript component does not have a method named: \"select\"'JavaScript component does not have a method named: \"select\"' when calling method: [nsITreeSelection::select]", result: 2153185328, filename: "chrome://global/content/elements/tree.js", lineNumber: 146, columnNumber: 0, data: null, stack: "MozTreeChildren/<@chrome://global/content/elements/tree.js:146:26\n", location: XPCWrappedNative_NoHelper }
tree.js:146

I hope this is what you were asking for :-)
Thanks for your help,
Roger V.
​

**Comment by opto** [comment]
please try 3.0.8, is ok here

**Comment by rogerval** [comment]
Version 3.08 seems to have fixed this; thanks for your hard work! :-)
