### ISSUE TITLE
Impossible to go to another folder after displaying the context menu of a folder in the folder pane

### ISSUE THREAD

**Issue by ThierryArx** [opto/nostalgy-xpi#127]
Once you have displayed the context menu of a folder in the folder pane, it becomes impossible to go to another folder (with mouse or shortcuts).
To solve the point - temporarily - I have to restart TB.

My current configuration:
Windows 10 1909
TB 78.13.0 (32 bits)

Thanks!

**Comment by jr-bennett** [comment]
Same problem confirmed on:
Windows 10 21H1
TB 91.02.2 (64 bit)

**Comment by tehcaster** [comment]
Same here with 3.0.7 on Linux 64bit, TB 91.0.1
The new option to detect message pane doesn't make a difference.

**Comment by DrBoym** [comment]
Same here! 
3.0.7 TB91
TB 91.0.3
Tried activate and deactivate Plugin, or disable Folder Pane view and reactivated it. Doesn't help either. 
Folder Pane simply freezes once you used the context menu.

**Comment by Olifair** [comment]
It's also the context menu on an email directly. I tested : 
with Nostalgy activated : I right-clicked on an email, choose "Show email in discussion", a new tab opened with all the emails of the discussion. By just doing this, and now selecting an email, the "respond" button would not work any more. Going back to the main tab, TB is frozen, no change in folders is possible, also not possible to edit a new email. It is not only the folder pane which is frozen, one also cannot go into the menu/messages/new message will not work. 
I have done the same thing with Nostalgy disabled (I disabled and then restarted TB with nostalgy disabled) : chose and email, view in discussion, was able to respond, go back to main, change folders, no problem. 
So this is clearly a Nostalgy problem

**Comment by opto** [comment]
yes, I can confirm the problem. I will see what broke this.

Klaus

**Comment by opto** [comment]
please try 3.0.8

we had a function with same name as in core TB and TB jumped into ours instead of its own.

**Comment by ThierryArx** [comment]
\o/
3.0.8 saved my life :-)
Thanks a lot opto, you got it!
Now, let's confirm it is also OK for other people who met the issue and then we can close the case.

**Comment by Olifair** [comment]
seems to be working now in Ubuntu and TB 78.13 , many thanks. I will test on windows 10 later this week-end (or on monday ...) 
Thanks for your efforts of keeping Nostalgy running.

**Comment by Olifair** [comment]
Also works on windows 10, TB 78.14.0 , however with the difference that I had to stop and restart TB to make it work (just installing would still result in TB freezing after right click menu on an email, e.g. show as discussion).

**Comment by opto** [comment]
".. restart TB..."
that may well be. Some code is only released on startup, even if we load it anew
