### ISSUE TITLE
Thunderbird freezing

### ISSUE THREAD

**Issue by Olifair** [opto/nostalgy-xpi#130]
I'm running Thunderbird 78.14.0 with nostalgy-xpi 3.0.7, only standard options, I have only the statistical prediction enabled. 

And I'm observing that about once or twice a day Thunderbird will just freeze. I can open and close the hierarchy of mailboxes, but clicking on any folder will not change the emails shown in the email panel and I can also not use any menu points. I think that I only observe this behaviour since installing 3.0.7.  To test I would need to disable nostalgy probably for a whole day. And as nostalgy is crucial to my email functioning, I hesitate to do this. And before doing this I just wanted to know if anybody else is also observing such freezing moments. 
Cheers
Oliver

**Comment by Olifair** [comment]
I just worked my way for 30 minutes through my mailmbox, using s and shift+s a lot. I did not open any contextual menu. And still, now the email pane is frozen as describe in #127 . I also cannot edit a new email. But I can for example open the adress book . Funnily I can do a general search (ctrl+shift+F), search and then do a "open in the folder", which then will switch to the folder and I can see the emails, but I still cannot change folders manually or write a new email. Only closing TB and restarting will get it working again.

**Comment by Olifair** [comment]
I have posted more detailed informations in #127 : 
https://github.com/opto/nostalgy-xpi/issues/127#issuecomment-924959811

**Comment by opto** [comment]
please try 3.0.8

**Comment by opto** [comment]
please try 3.1.3 https://github.com/opto/nostalgy-xpi/releases/tag/v3.1.3

swich off the ption for conversation /thread search if necessary

**Comment by opto** [comment]
@olifair  I think this is working with 3.1.3, if not, please reopen the issue

**Comment by Olifair** [comment]
@opto I haven't had any freezing problems for a long time now, probably beginning of December. Actually I don't see any of the problems that others have described lately, everything is just running fine (except perhaps statistical prediction ;-) So I suppose 3.1.3 won't change anything, only otherwise I will report back. Thanks for all the effort you are putting into Nostalgy++
