### ISSUE TITLE
Release Versions and rebind keys as enhancement

### ISSUE THREAD

**Issue by hkclark** [opto/nostalgy-xpi#132]
I have been wondering why the version in the "Thunderbird Add-ons Site" is still at 3.0.4 -- https://addons.thunderbird.net/en-us/thunderbird/addon/nostalgy_ng/.  It seems like keeping that up to date would help people "auto upgrade" to the latest version of Nostalgy and get bug fixes and new features.  Apologies if this is the wrong place to ask this but I wasn't able to find another place.  Thanks for keeping Nostalgy alive!

**Comment by opto** [comment]
it was unclear whether some OS (Mac? Linix?) have some problems at startup.

Currently, there is no TB given way to truely wait with our addons until TB has finished its startup

**Comment by hkclark** [comment]
@opto OK thanks.  So once that's resolved you will start pushing releases here to the normal TBird Add-on Site?  If so, that makes sense.  Again, sorry to bug you with the question... it's just had me confused for a while. :-)

**Comment by opto** [comment]
if you are interested, please try this:
https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.10

**Comment by internationils** [comment]
would it be possible to register a key combo or something that will allow the addon to refresh / re-register all of its key bindings to work around this issue? Or what is the issue with needing to wait for the TB startup? Thanks...

**Comment by hkclark** [comment]
I'm thinking this can be closed.  Thank you.
