### ISSUE TITLE
When pressing 'S' the suggestion text box should be pre-filled with the suggestion from the rules

### ISSUE THREAD

**Issue by Tvangeste** [opto/nostalgy-xpi#135]
I think that's how the original nostalgy worked.

For example, let's say I have a rule that for emails starting with "yay" they should be in "YAY" folder.
When I select such message, I see in the notification bar below that indeed: [+Shift => YAY].
But if I press S, I am greeted with an empty text box, which is weird. It should be pre-filled with "Yay" and I could double-check the correctness of the destination and press enter, as I used to do in the older versions of the plugin.

Thank you for keeping this awesome plugin alive and improving it, btw. MUCH appreciated!

**Comment by opto** [comment]
if you press shift-S, then there happens exactly what you want.
S offers the normal folder selection box because:  ... this mail might need to go elsewhere.
In other words, it is needed to override the suggestion.

Klaus
