### ISSUE TITLE
two mins to help a clueless person?

### ISSUE THREAD

**Issue by ProfChunes** [opto/nostalgy-xpi#14]
been redirected from elsewhere, hate to open an issue for a minor q, but here's my messasge 

Folks, I really really appreciate the work on this! Opened a github account just to access opto's fix.

If anyone had a spare minute to help a clueless person: I'd like to change the hot key for move message from 's' to 'm' (since I use 's' for star message). The little I know about coding tells me that there might be a line somewhere the opto file set where I could simply replace one letter with another and recompile. True? Where would I look?
Cheers, Andy

**Comment by IGZmanuelMartinVivaldi** [comment]
I´ve just tested Nostalgy options and it worked.

Go to: Tools menu/Nostalgy and select Keys

Click on the 'S' and press 'M'. Accept and done

**Comment by ProfChunes** [comment]
thanks, both. however, whilst I can change they keys ok, the selection doesn't save after I've hit OK

**Comment by IGZmanuelMartinVivaldi** [comment]
For me is saving the new assigned key and working.

Tested on Thunderbierd 68.3.0 (Windows 10) and Nostalgy 0.393

**Comment by ProfChunes** [comment]
So I see this screen, press OK and it does not save 
![image](https://user-images.githubusercontent.com/58812260/70911722-61281500-200a-11ea-9be9-276dddbc5729.png)

**Comment by IGZmanuelMartinVivaldi** [comment]
It works fine for me after modifying the key I Accept and the ney Key it's saved:
![image](https://user-images.githubusercontent.com/2234919/70917323-6773bc80-201d-11ea-9ee2-a9154e400f05.png)

**Comment by ProfChunes** [comment]
thanks - yes that's what I did. did your dialogue box look like mine?
My only other addon is Exquilla, not sure if htat might make a difference?

**Comment by MLopez-Ibanez** [comment]
> thanks - yes that's what I did. did your dialogue box look like mine?
> My only other addon is Exquilla, not sure if htat might make a difference?

The label in the status bar is a fixed text that doesn't depend on the actual keys:

https://github.com/MLopez-Ibanez/nostalgy/blob/7929061852f3f664372cf5ef7dbaf7f2e3ce90ac/chrome/content/messageOverlay.xul#L46

If you know or find out how to make it depend on the shortcut, I'm happy to make the change.

**Comment by MLopez-Ibanez** [comment]
In my version, changing the key in the menu does work but it doesn't change the status bar text.

**Comment by MLopez-Ibanez** [comment]
If the dialog box doesn't save, perhaps you can see in the console output or the error console an error exactly at that moment?

**Comment by ProfChunes** [comment]
Thanks all for help. Last bit of coding I did was when I updated my fortran77 model to f90, so...

Relevant error console output is in amongst this lot:

1576663053281	addons.xpi	WARN	Failed to parse recommendation: {"operation":"open","path":"C:\\Users\\Andy Challinor\\Documents\\GitHub\\nostalgy\\mozilla-recommendation.json","winLastError":2}
WebExtensions: Loading unpacked extension from C:\Users\Andy Challinor\Documents\GitHub\nostalgy ext-legacy.js:160
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:5
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:7
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:9
WebExtensions: Loading add-on preferences from  C:\Users\Andy Challinor\Documents\GitHub\nostalgy ext-legacy.js:190
WebExtensions: Firing profile-after-change listeners for nostalgy@alain.frisch ext-legacy.js:194
Overlays.jsm: Could not resolve 1 references 

no idea what do do next though. As I workaround, am happy to change the "star" key from 's' to something else... but I don't know how to do that either.

Incidentally I'd happily pay a subscription for nostalgy; already do for Exquilla.

**Comment by opto** [comment]
works in 1.0.16a on win10 home. Please retry

**Comment by ProfChunes** [comment]
Sorry, opto - proper clueless like the title of thread says.. :-o

Just refeteched TB68 branch, but files seem to all be the same as before. Tried it anyway.. still doesn't work

not sure what your version no 1.0.16a refers to... 

in case it makes a difference:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18363 Build 18363

**Comment by ProfChunes** [comment]
The following from opto fixed this. I only had to change "g" to "G" and similar for other keys, as lower case did not work for some reason. Thank you all so much.

new version 1.0.16a at releases at https://github.com/opto/nostalgy-xpi/releases (use the xpi, the zip is still old).

This version covers about everything except:

    box showing previous folders not active. Didn't work in TB 60 as well.
    but workaround: shift-S moves to last folder if no rule exists

This now works:

    basic s, c, g, l, etc.

    links from messages are now shown in status line (thanks MLopez-Ibanez)

    messagedisplay in window allows s, c

    esc f, esc m, esc esc, esc esc esc are ok, but a bit tricky in timing (best if esc and f pressed shortly after each other)

    keys can be set

    in tab utilities: restart button (helpful if many windows are open - no need to close them separately)

    more to come: e.g. move email and create new rule

Please report issues at https://github.com/opto/nostalgy-xpi/issues
