### ISSUE TITLE
Nostalgy++ keyboard shortcuts

### ISSUE THREAD

**Issue by jugglesmiles** [opto/nostalgy-xpi#140]
I am using Nostalgy++ 3.0.4 with Thunderbird 91.3.2. on Windows 10, Initially, all the keyboard shortcuts of Nostalgy++ work fine, but then they stop working after a couple of minutes. I can either disable Nostalgy++ and then re-enable it or, alternatively, restart Thunderbird - and then the cycle repeats. Sometimes, the keyboard shortcuts work for a much longer time.

This must be due to a new version of Thunderbird or Nostalgy++. Things worked fine a couple of months ago.

**Comment by Olifair** [comment]
I have also Thunderbird 91.3.2 on Windows 10, but I have Nostalgy++ 3.0.8 installed, I do not observe any such problems. Try to install 3.0.8. Or perhaps this is an interaction with other extensions ?

**Comment by watho** [comment]
Its a known problem. The following text is from the details pane of the addon

```
Attention for TB 78.11/TB 78.12/Thunderbird 64 bit:
There have been timing problems in TB when using the 64 bit version of Thunderbird.
3.0.4 should solve these problems. If it does for you, please ignore the following remarks.
Otherwise, please comment on github or send info to the support email.

For version 2 in TB 64 bit: on TB loading, TB first sets Nostalgy keys, and after that, it sets its own TB keys, overwriting the keysetting of Nostalgy.
In earlier versions of TB, TB did wait with loadiing of addons until TB itself was ready.

That means after TB start, out of the box, the keys do not work.
There is a workaround: open TB addons page (tools-> addons), deactivate Nostalgy++ with the blue slider switch, then reactivate Nostalgy++. Now it sets its key after TB is ready and they stay until the next restart.


3.0.4 should solve this for TB 78 and TB 91. On win 10, the problem only comes up in 64 bit TB, 32bit TB works fine.
```

**Comment by watho** [comment]
I just encountered that 3.0.4 should have solved the issue. For the me and @jugglesmiles the problem still persists.

**Comment by opto** [comment]
please try 3.0.11 from these github pages:  https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.11

**Comment by opto** [comment]
TB team (John) helped to optimise startup, I am interested whether this solves the problems.
https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.17

Klaus

**Comment by opto** [comment]
pre 115, outdated
