### ISSUE TITLE
Nostalgy++ usage button stopped working at least in 3.10

### ISSUE THREAD

**Issue by cjholly** [opto/nostalgy-xpi#142]
I cannot get my nostalgy usage instructions to open. I see the button, but nothing happens when I click it. I will try to upgrade to 3.11 and see if that matters --Chris

**Comment by opto** [comment]
works here with TB 91.4.1 and 3.0.11. Using the button in the status bar on win 11 64 bit

How about at your end?

Klaus

**Comment by opto** [comment]
today, it does not work with 91.4.1, so it seems to be an intermittent bug.

TB gives a 'very helpful' message: 'Error: An unexpected error occurred'.

Klaus
