### ISSUE TITLE
Esc-1 does not open pdf attachment in 3.10

### ISSUE THREAD

**Issue by cjholly** [opto/nostalgy-xpi#143]
At least in 3.10, when I am highlighting a message in the list or in the message pane, Esc-1 does not open the attached pdf file. The error message says no image file found, or something close to that. --Chris

**Comment by opto** [comment]
this only works for images, not for pdf. Also, I tested that is does not work for inline images, only for true attachments.

You can try my addon attachment viewer, that can show pdf and office files without having to open the native application
https://addons.thunderbird.net/en-US/thunderbird/addon/attachment-image-viewer/?src=hp-dl-upandcoming

Klaus
