### ISSUE TITLE
V3.1.3 and 3.0.11: hotkeys interfering (again) with calendar (events and tasks)

### ISSUE THREAD

**Issue by ungeahnt** [opto/nostalgy-xpi#144]
same problem as #81:

> It seems that N++ is activating while in the calendar tab on Thunderbird. e.g. if I try to create a new event with the first letter being "s", it moves the focus to the N++ "Move messages to: "entry box at the bottom of the screen.
It would be good for it to be inactive in the calendar tab.

I use Thunderbird 91.5.0 (32bit) / Win10Pro_x64

**Comment by opto** [comment]
set option: restrict commands to email tab. Does that help?

**Comment by ungeahnt** [comment]
Thanks for the quick reply. It seems to be fixed with the option 'restrict commands to email tab'.

... but, I've looked for information about the 'restrict'-option and with release 3.0.7 you mentioned:

> '... because recognising tab type was not totally reliable.' 

Please, can you tell me what _'not totally reliable'_ means?

**Comment by ungeahnt** [comment]
First of all, thank you very much for your engagement and work. For me, Nostalgy is the most important tool for Thunderbird!

Basically it works with the option, but somehow nostalgy and the new TB keep getting stuck in different places and it's hard to reproduce the errors and assign them to a specific feature. I am still testing and will let you know.

**Comment by internationils** [comment]
I would add another Tab to this. When looking for addons I landed on an addon page https://addons.thunderbird.net/en-US/thunderbird/addon/mailbox-alert/?src=search and when trying to type into the "search for addons" field the keys are used by nostalgy (i.e. "n" opens the Nostalgy preferences)

**Comment by opto** [comment]
@internationils    does that help for you:
set option: restrict commands to email tab?

**Comment by internationils** [comment]
@opto yes that helps, fixes it for me. I think that should be the default option (unless there is a good reason to have nostalgy commands in other tabs).

**Comment by opto** [comment]
will be preset for new installs

new version: https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.3

**Comment by internationils** [comment]
For me you could close this bug... @ungeahnt agree?

**Comment by ungeahnt** [comment]
the option works for me
