### ISSUE TITLE
When to use v3.0.11 vs v3.1.3 and vice versa?

### ISSUE THREAD

**Issue by johnnyutahh** [opto/nostalgy-xpi#146]
Can anyone characterize guildelines for when to install v3.0.11 vs v3.1.3?

There may be lots of docs, but it appears there's a lot of work to boil down the differences and/or applicability/risks/general_comparison of each. I'm looking for shorter, maybe "bulleted" summary, if that's feasible and reasonable to make?

I run Thunderbird 91.5.0 (64-bit) on macOS 10.14.6.

**Comment by johnnyutahh** [comment]
Roger that, thanks. Can v3.1.3 do everything that v3.0.11 can?

I run Thunderbird 91.5.1 (64-bit)--upgraded from 91.5.0 just today--on macOS 10.14.6.

**Comment by opto** [comment]
the newest version should have all functionality
