### ISSUE TITLE
[Solved] How to fix broken 'Statistical prediction' (Thunderbird v91.x, Nostalgy++ v3.0.11) after migrating to new IMAP-service provider?

### ISSUE THREAD

**Issue by johnnyutahh** [opto/nostalgy-xpi#147]
fyi. Reference to procedure I wrote for an issue Alain Frisch's Nostalgy repo:

https://github.com/nostalgy/nostalgy/issues/108#issuecomment-1019656386

**Comment by opto** [comment]
close because [solved]
