### ISSUE TITLE
Non compatible with TB 68.3.1 (64-bit macosx)

### ISSUE THREAD

**Issue by Temistocle** [opto/nostalgy-xpi#15]
Just unsuccesfully tried to install add-on from file on TB68.3.1 64-bit Mac OS X 10.13.6 High Sierra.

**Comment by mdonz** [comment]
You might want to describe the issue in more detail? Maybe an error message? Have you checked #7?

**Comment by Temistocle** [comment]
Thank you @mdonz  for the suggestion of #7. It was quite a similar case. But some minutes ago the fresh new nostalgy1.0.16 installed immediately also in TB68.3.1 64-bit on my Mac OS X 10.13.6 High Sierra.

**Comment by mdonz** [comment]
Good to know. I would be curious whether you experience with that version issue #18 ?

**Comment by Temistocle** [comment]
If I'm not misunderstanding #18, maybe I'm experiencing it: e.g. pressing _s_ o _g_ only gets a blank window appear  below the bottom status bar, without cursor focus; anyway, by clicking on it and beginning to type, nothing happens.

**Comment by mdonz** [comment]
MY most often used Nostalgy keys are "`" (select by subject or sender) in my Inbox, then highlight that selected group of emails and then the "s" key to save (move) these emails to a folder name that I select then. None of these keys "`", "s" are working at the moment unfortunately with that version.

**Comment by Temistocle** [comment]
This morning, nostalgy1.0.16a was released and everything seems ok (list of folder paths that match typed in characters, moving messages, changing displayed folder) !  

> If I'm not misunderstanding #18, maybe I'm experiencing it: e.g. pressing _s_ o _g_ only gets a blank window appear below the bottom status bar, without cursor focus; anyway, by clicking on it and beginning to type, nothing happens.
