### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by jxcx** [opto/nostalgy-xpi#150]
With any 3.2.* version there is a memory leak. Top says ...
        PID    PR  NI    VIRT    RES          SHR S  %CPU  %MEM     TIME+   COMMAND
    1729781 20   0 2746284 160852 115724 R     93.8      0.5        0:00.52   thunderbird
    1729781 20   0    10.2g   4.6g      197824 R   106.2    14.6        1:45.13   thunderbird
    1729781 20   0 3702580 446056 200192 R   106.2      1.4        1:46.90   thunderbird
    1729781 20   0 3707932 427244 200496 S      0.0       1.3        1:47.36   thunderbird
Thunderbird freezes and then responds at 1:47.
Versions 3.1.* are OK.
This is on ubuntu linux 20.04, kernel 5.4.0-97-generic, thunderbird 91.5.0.

**Comment by opto** [comment]
Hello, is this reproducible? If yes, please attach a copy of the error 
console.

If you switch  off the detection of conversations and threads (in the 
otions), does it happen as well? There are only minor changes between 
3.1.* and 3.2.*.


thanks, Klaus.

**Comment by jxcx** [comment]
Hi Klaus ---

3.2.6 does not help.
All options are off.
Shell log and error console follow.
[log.txt](https://github.com/opto/nostalgy-xpi/files/8007516/log.txt)

--- joe

**Comment by opto** [comment]
https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.8

**Comment by jxcx** [comment]
Hi Klaus ---
The problem is solved in 3.2.8, thanks so much!
--- joe
