### ISSUE TITLE
Slow Thunderbird start and massive memory usage during startup

### ISSUE THREAD

**Issue by sphh** [opto/nostalgy-xpi#151]
After upgrading Nostalgy from 3.0.x(?) to 3.2.3 or 3.2.4 starting Thunderbird takes a very long time and consumes all available memory and a lot of CPU usage. The windows manager shows the window, but it has no size and it cannot be switched to. After waiting a long time, the Thunderbird windows appears, the CPU load and the memory consumption is back to normal.

When I start Thunderbird from a terminal, I get some debug outputs, and then after the wait a message `Thunderbird is starting` and the window finally appears.

Possibly related to #150?

Thunderbird 91.5.0 (64-bit)
Manage Emails/Nostalgy++ 3.2.3
Linux Mint 20.2

Nostalgy Preferences > Completion
☐ Restrict folder completion to the current server
☐ Match only on folder name, not on the full path
☐ Match only the prefix of folder path or name, not any substring
☑ Sort folders alphabetically
☐ Match folder names in a case sensitive way
☑ Tab triggers shell-like completion (otherwise, cycle through suggestions)
☐ Always include tags
☑ Use Statistical Prediction
☐ Suggest folder of related conversation
☑ Restrict command to email tab
Number of recent folders to remember: 5
Number of folders to show in completion: 25
Width of folderbox (characters): 70
Number of addresses to consider for statistical prediction: 100

**Comment by opto** [comment]
please try this one:
https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.6

I had already planned to load the scripts after an inject but found it to big a change up to now.

But here, it solves the fact that window is not ready at startup.

2 questions:
* gDBView should show something, now
* is it still hanging?

**Comment by sphh** [comment]
I just downloaded and installed version 3.2.6.

Unfortunately the start up behaviour has not improved, but I was able to capture the console output:
```
console.debug: "CompleteInit: DONE"
[LONG WAIT]
console.log: "mainWindow"
console.log: "gDBView" null
console.log: "nostalgy_in_message_window" false
```

**Comment by sphh** [comment]
With the update to v3.2.8 this problem went away. Thunderbird starts immediately! Thanks for investigating and solving this problem, @opto!

I consider this solved and hence will close the issue.
