### ISSUE TITLE
Thunderbird hangs after updating of Nostalgy++

### ISSUE THREAD

**Issue by sphh** [opto/nostalgy-xpi#152]
I downloaded the new release from github and use `Add-ons Manager > Install Add-on From File ...` to install the downloaded `.xpi` file.

After confirmation to install the add-on, everything goes well until I am asked to confirm `Manage Emails/Nostalgy++ was added` with the `Ok!` button. There not only the `Ok!` button does not respond, but I cannot even switch to _any_ other window. I had to go to the virtual terminal (`Ctrl-Alt-F1`) and kill Thunderbird from there.

I also noticed that Thunderbird uses a lot of CPU resources and all available memory, similar to the behaviour described in #151.

After starting Thunderbird again, I experience the behaviour described in #151.

I observed this for version both 3.2.3 and 3.2.4, but these I have not installed any other version from the 3.2 branch.

The error messages I get starting with the installation are:
```
console.debug: "onTabSwitched: title - Loading\u2026"
console.log: "gDBView" ({})
Exiting due to channel error.
Terminated
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
```

Thunderbird 91.5.0 (64-bit)
Manage Emails/Nostalgy++ 3.2.3
Linux Mint 20.2

Nostalgy Preferences > Completion
☐ Restrict folder completion to the current server
☐ Match only on folder name, not on the full path
☐ Match only the prefix of folder path or name, not any substring
☑ Sort folders alphabetically
☐ Match folder names in a case sensitive way
☑ Tab triggers shell-like completion (otherwise, cycle through suggestions)
☐ Always include tags
☑ Use Statistical Prediction
☐ Suggest folder of related conversation
☑ Restrict command to email tab
Number of recent folders to remember: 5
Number of folders to show in completion: 25
Width of folderbox (characters): 70
Number of addresses to consider for statistical prediction: 100

**Comment by watho** [comment]
Same issue here with 3.2.4

> There not only the Ok! button does not respond, but I cannot even switch to any other window. I had to go to the virtual terminal (Ctrl-Alt-F1) and kill Thunderbird from there.

Especially this worries me. I know no other program happens to achieve this ever.

**Comment by opto** [comment]
this does not happen on win 11 on a fresh install.

Especially this should not be empty, it should (and does here) output the view:
console.log: "gDBView" ({})

For you, it is empty ( {}  )

**Comment by sphh** [comment]
Is there a way, I can help you to figure out, why `({})` is empty (on my installation), so that it can be filled with some sensible contents?

**Comment by opto** [comment]
I also get an undefined gDBView (but no hanging) if I use your settings. 

I will check which setting it is.

**Comment by opto** [comment]
ok, it is the old problem: after a restart, TB does not tell us reliably when it main window is ready.

So in 3.2.4, we want to store and log window.gDBView, but window does not exist yet. These problems come on and off, and nobody has yet understood why (including the helping person from the TB team). It is a racing condition: if TB's internals are not ready when we overlay them, then we have this problem.

Whether it is related to the hanging: no idea, no hanging on win 11.

**Comment by opto** [comment]
please try this one:
https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.6

**Comment by sphh** [comment]
I just downloaded and installed version 3.2.6. Thunderbird hanged again at the same point, so I killed it, restarted it and installed version 3.2.6 again.

Here is the console output:
```
console.debug: "onTabSwitched: title - Add-ons Manager"
JavaScript error: undefined, line 0: Error: Not a valid compose window
console.warn: services.settings: Failed to load last_modified.json: TypeError: NetworkError when attempting to fetch resource.
JavaScript error: undefined, line 0: Error: Not a valid compose window
console.debug: "onTabSwitched: title - Loading\u2026"
[KILL]
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Terminated
```

**Comment by opto** [comment]
do you have a compose window open?
what happens if you close all tabs except the mainmail tab before restart?
thanks, Klaus

**Comment by sphh** [comment]
No, there is no compose window open. Just the main Thunderbird window with the following tabs:
- Main mail tab
- Calendar
- CardBook
- Add-ons manager
- Message 1
- Message 2
- Add-ons internet page addons.thunderbird.net

The strange thing is, if I close all tabs but the first before closing Thunderbird, they reappear when starting Thunderbird again (after the long wait). Do you know, how to close them permanently?

But I tried something different:
1. I disabled the Nostalgy++ add-on.
2. I closed all tabs, but the main mail tab and the add-ons manager.
3. I then enabled Nostalgy++ again.

I get the same behaviour (high CPU load, memory consumption until there is no memory left, then a sudden reduction of CPU load and memory consumption drops back to a level close to that before I enabled Nostalgy++. The terminal output is
```
console.debug: "AddonListener.onEnabling"
console.log: "mainWindow"
console.log: "gDBView" ({})
console.log: "nostalgy_in_message_window" false
JavaScript error: undefined, line 0: Error: Not a valid compose window
```

**Comment by sphh** [comment]
Thanks @opto! Now the `Ok` button becomes responsive immediately after the update, no (excessive) CPU usage and the memory consumption stays the same.

I consider this resolved. Thanks again.
