### ISSUE TITLE
Save (s) moves 100 messages only

### ISSUE THREAD

**Issue by ivosir** [opto/nostalgy-xpi#154]
Hi Klaus (@opto), the Save function is now limited to 100 messages only, is it on purpose? How to reproduce the issue: select more than 100 messages, hit s (or ctrl+s), only 100 messages will be saved/moved to the destination folder, 101+ will remain in the source folder. I am on TB 91.5.0, Nostalgy++ version 3.2.16.

**Comment by opto** [comment]
thanks, ivosir.

move is now done by the new webextension code. I was not aware that it moves 100 emails, only.
I know that if I list a folder, i get pages of 100 (because it has to search), but here, we only look at the seleted emails.

I will ask TB people.



Klaus

**Comment by opto** [comment]
sorry, I oversaw that and will change it to iterate through all parts of the message list

**Comment by opto** [comment]
for move > 100 messages and mouse up bounce for mouse gesturees, please try: https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.18

**Comment by ivosir** [comment]
Yes, version 3.2.18 moves all messages again. Many thanks, I appreciate your efforts!

**Comment by opto** [comment]
I forgot to update the copy for +100 msgs, that is in 3.2.19, coming ca. today

**Comment by opto** [comment]
reverted back to the old copy, because the new has no undo. and: TB team (John) helped to optimise startup, I am interested whether this solves the problems.
https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.17

Klaus
