### ISSUE TITLE
N++3.2.16 mostly compatible with TB98 beta (if strict_max_version is adapted)

### ISSUE THREAD

**Issue by internationils** [opto/nostalgy-xpi#156]
I am trying out the TB 98b2 currently, and Nostalgy++ 3.2.16 is not compatible. Is it possible to have the version open to use with Betas, or to have another version that one can explicitly install? Thanks!

**Comment by opto** [comment]
are you familiar with zip/unzip? Then you can easily do it yourself:

download the xpi, unzip it (it is actually a zip with the name xpi).
open manifest.json with a text editor. Adjust strict;max_version to 98.0

Rezip. For testing, you don't even need to rename it: goto addons, install from file.

I didn't try it on 98 yet, if you can report your results, that would help and I would appreciate that.

Klaus

**Comment by opto** [comment]
there is some inclarity for me on the versions o use for betas. Could be 98.0 or 99.0. 98.b or similiar does not work.

**Comment by internationils** [comment]
https://github.com/opto/nostalgy-xpi/releases has 3.2.8 as the latest version, but I am running 3.2.16 already, where do I get the XPI?

Ah, found it, it came from https://addons.thunderbird.net/en-US/thunderbird/addon/nostalgy_ng/ ... thanks for updating it there!

**Comment by internationils** [comment]
Thank you for updating Manage Emails/ Nostalgy++. You are now running version 3.2.16 on Thunderbird 98.0.

It works, as long as you zip all the files directly into the XPI and not the folder you extracted them into : )

I will leave this open in case I find issues, else will close in a few days

**Comment by opto** [comment]
I understand that it is mostly compatible, so I have changed the title of the issue.
