### ISSUE TITLE
Why did a TB v91.6.0 --> v91.6.1 upgrade force a Nostalgy++ v3.2.0 --> v3.2.16 upgrade?

### ISSUE THREAD

**Issue by johnnyutahh** [opto/nostalgy-xpi#159]
I recently upgraded Thunderbird from `v91.6.0 --> v91.6.1`, and this TB-only upgrade appeared to "force" a Nostalgy++ `v3.2.0 --> v3.2.16` upgrade.

Is this expected behavior?  If so, why?

I would prefer that I get to choose when to upgrade add-ons, not Thunderbird.

Thoughts?

**Comment by opto** [comment]
I think thaat is incidental, not planned.

In the addon page, you can set how addon updates are done: automatic, manually, not at all.
with Kaspersky, that doesn't work (no updates ever). So I never tested that.
It is at the botton of where the addon is described (extra->addons, click nostalgy++

**Comment by johnnyutahh** [comment]
1. I always mark `Allow automatic updates` as `Off` for all my Thunderbird Extensions/Add-ons.  
2. I've executed at least 1 previous Thunderbird v91.x upgrade with Nostalgy++ installed, and the Nostalgy++ version did not auto-update.

(Apologies, I should have mentioned these things in my original post.)

Why is the auto-update just starting to happen now?  I have not tested to see if it's consistent behavior... because I have not rigoursly tested the TB updates behavior.

@opto writes:
> with Kaspersky, that doesn't work (no updates ever).

What is "Kaspersky" and how does it apply here?  I thought it (Kaspersky) was some anti-virus and related software. I do not use it.

**Comment by opto** [comment]
if it updates with automatic updates set to off, that should be reported in bugzilla as a TB bug
Kaspersky is a Windows virus software. As I learned recently, all update processes are strongly influenced by security, certificates, which need to be accepted and transfered by the virus software, and for addons, Kaspersky is a man in the middle which refuses to accept the certificate or the update server for addon update (they do for TB update)
Somy addons only update when I switch off Kaspersky for a few minutes.

**Comment by johnnyutahh** [comment]
This still happens. I realize it may not be a Nostagly++ specific issue. When I updgraded TB to v91.8.1 it auto-upgraded (without my consent) Nostalgy++ from v3.2.0 to v3.2.17.

**Comment by opto** [comment]
you can set addons to not update. If that does not work, please file a bug at Thunderbird/bugzilla.
