### ISSUE TITLE
Focus on Nostalgy field when opening message list

### ISSUE THREAD

**Issue by PointInSpace2** [opto/nostalgy-xpi#16]
When opening the message list window, the Nostalgy field appears at the bottom and focus is there.  Makes it impossible to use TB key commands until clicking in the message list to dismiss it.  Possible to keep this from happening?

**Comment by opto** [comment]
should be ok in 1.0.16a

**Comment by PointInSpace2** [comment]
Still seeing this with 1.0.16a, sorry to say.  On macOS.

**Comment by benlundmaine** [comment]
I'm using TB 68.4.1 on Windows 10 and see the same issue.  The field can be dismissed by hitting the Escape key.  Thanks for all of your work.

**Comment by teledemic** [comment]
Yeah I get this all the time on 1.0.16a, mac

**Comment by benlundmaine** [comment]
Solved for me (Windows 10, TB 68.4.2, 64 bit) by most recent release.  Thanks!
