### ISSUE TITLE
How to concurrently run 'tbkeys' and 'Nostalgy++' add-ons in v91.6.x or above without key-binding collisions?

### ISSUE THREAD

**Issue by johnnyutahh** [opto/nostalgy-xpi#163]
https://www.reddit.com/r/Thunderbird/comments/swsu0y/how_to_concurrently_run_tbkeys_and_nostalgy/

**Comment by opto** [comment]
I think tbkeys so seriously changes TB that that cannot work.

**Comment by johnnyutahh** [comment]
Thus far the combination (Nostalgy++ v3.2.0 and tbkeys v2.2.0) is working just fine, no problems.

More background:
https://github.com/wshanks/tbkeys/issues/64
