### ISSUE TITLE
Undo (ctrl-z) does not seem to work anymore

### ISSUE THREAD

**Issue by BjornW** [opto/nostalgy-xpi#165]
After I've moved a message, by typing the folder en pressing ENTER, the message is moved to this folder. In the past I could undo this by pressing the keys CONTROL-Z. This does not work, the message does not move back to the original folder.

**Comment by opto** [comment]
we are now using the 'webextension' way to move messages. I can only assue that that method does nnot have udo capability.

I will enquire with TB team.

**Comment by KennyReff** [comment]
Same issue here.  I sure hope it’s resolved. I’m a financial contributor because Nostalgy’s keyboard move command is invaluable!  But less so with this bug. Lemme know if I can help. Thanks!

**Comment by opto** [comment]
the new webextension version of move, does not hand over the window to the move process, so I think undo cannot work because the undo is a function of the window.
version 3.2.24 has reverted the move and copy to the old functions. here, undo works for move, but not copy. I don't know whether it ever worked for copy or not.

**Comment by opto** [comment]
https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.24

**Comment by BjornW** [comment]
@opto just tested it on my Linux machine with your 3.2.24 release and undo with CTRL-Z works as before. Donated 25 euro because this plugin is a huge productivity help. Thanks!

**Comment by KennyReff** [comment]
Darn! I was hoping v3.2.24 would solve it for me too.  But when I installed that version in TB Mac 78.13.0, none of my keyboard move shortcuts work at all.  In fact, Nostalgy doesn't even show up in the TB Tools menu.  It is listed as active in the add-on window so it's been installed.  But it's not showing up in the Tools menu to configure it.  Help please.

**Comment by BjornW** [comment]
@KennyReff your version of Thunderbird seems a bit old? Mine is 91.5.0. I think that might explain why it isn't working for you. A possible solution could  be updating Thunderbird to a more recent version.

**Comment by KennyReff** [comment]
Yeah, that's on purpose. I can't remember the issue, but some other important plug-in wasn't working with the later TB versions. But even with this TB version (78.13.0), Nostalgy v3.2.17 worked fine.  So shouldn't v3.2.24 work as well?

**Comment by BjornW** [comment]
@KennyReff not necessarily, but I'm not informed enough about the code to say something about that with any certainty ;) In general though it's better to keep software up-to-date.

**Comment by KennyReff** [comment]
Well, I took a chance on losing some other add-on functionality by upgrading to TB 91.6.1 and everything is more than fine!  Opto's Nostalgy v3.2.24 now allows the undo after moving an email with a shortcut, AND this newer version of TB FINALLY has a decent print preview function!  Yahoo!  @BjornW, thanks for the nudge.  And @opto, THANK YOU for Nostalgy!

**Comment by BjornW** [comment]
@KennyReff Good to hear. Glad it all worked out! I'm closing this now since the problems seems to be solved. Thanks @opto
