### ISSUE TITLE
"Go" stopped working with 3.2.17 in MacOS

### ISSUE THREAD

**Issue by PointInSpace2** [opto/nostalgy-xpi#166]
Using the Go function no longer goes to the folder in 3.2.17.  MacOS 11.6.4, TB 78.14.0.

**Comment by PointInSpace2** [comment]
It appears the last version that worked OK was 3.1.3.  And it looks like 3.1.4 had some "Go" changes made that must have messed it up for me?

**Comment by sinkva** [comment]
"Go" function is working properly for TB 91...
MacOS 11.6.1 (Big Sur)
Thunderbird 91.6.1 (64-bit)
Nostalgy++ 3.2.17

**Comment by robertlhawley** [comment]
Same issue for me as PointInSpace2- 'Go' offers the bar to type folder name, suggests options successfully, and then when I press enter, simply doesn't 'go' there!
CentOS 8
Thunderbird 78.6.1
Nostalgy++ 3.2.17

**Comment by opto** [comment]
are you in 'all' view? Does it work there?

**Comment by robertlhawley** [comment]
Wow- quick response!  I think I am in 'all' view; (View -> Folders -> All).  In case it matters, I'm also in 'Classic' Layout with the folders pane.  Let me know if other parts of the view or interface details will help!

**Comment by Olifair** [comment]
I'm running TB 91.6.1 32bit and Nostalgy++ 3.2.17 on a windows 10 64bits laptop and I do not seem to have any problem, s,g,b and shift+s,g,b and alt+g work as expected from the main window (and I'm not using any folder filters, always showing all folders). I'm having a few other extensions installed (Copy Message ID, Copy Sent to Current, FiltaQuilla, ToggleHeaders) and they do not seem to interfere. I have tried to use the keys from the IMPA inbox to other IMAP folder and to local folders, all working.

**Comment by opto** [comment]
please try this, it works on win 11 TB 64 bit

**Comment by opto** [comment]
https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.22

**Comment by PointInSpace2** [comment]
3.2.22 doesn't work at all here.  The wrench button in the addon settings even disappears.  No key commands function.

**Comment by PointInSpace2** [comment]
Hmm, now when I reloaded 3.1.3 the Go function is working properly.  Odd.

**Comment by opto** [comment]
newest https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.24

**Comment by opto** [comment]
this TB error message (actually, it is a warning only) may help:
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="g" Modifikatoren="accel,alt" ID=""

key event is not available in some keyboard layouts: key = g, modifiers: accel, alt

you can choose other letter in options, does that help?

**Comment by PointInSpace2** [comment]
Same experience - this new version doesn't work at all on my install.

**Comment by opto** [comment]
how about this: please try this https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.2?

I discovered that writing logs took much time in Ubuntu, so it may have blocked the expected actions and may have caused race conditions.

please als try the new search (searchglas with ++ in top right)

**Comment by PointInSpace2** [comment]
Go is still not working

**Comment by opto** [comment]
TB team (John) helped to optimise startup, I am interested whether this solves the problems.
https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.17

works here on win 11 and Ubuntu 20

Klaus

**Comment by opto** [comment]
new version: https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.19

**Comment by PointInSpace2** [comment]
Still not working, sorry.

**Comment by PointInSpace2** [comment]
After updating Thunderbird to v91.8.1 and the newest Nostalgy 3.3.21, everything seems fine now!
