### ISSUE TITLE
CPU Utilization

### ISSUE THREAD

**Issue by hkclark** [opto/nostalgy-xpi#171]
Has anyone else noticed that one of their CPU cores is pegged at 100% utilization as soon as they enable nostalgy-xpi?  I'm on Windows 10, Thunderbird 91.7.0 64-bit and using `manage_emails_nostalgy_pp_3.2.24-tb.xpi`.  If I create a new Thunderbird profile with no email or anything, it seems OK, but I haven't been able to figure out where the issue is coming from.  I have disabled all other addons and it still behaves the same way -- as soon as I enable Nostalgy++ my fan ramps up and one of my CPU cores is constantly at 100%.  I have been getting this for about a week if I recall correctly.

**Comment by opto** [comment]
we are using a way to identify threads/conversations which was reported elsewhere to create waiting times in the past (=high CPU load?):

It is based on TB functions, you can only try to switch it off: in the options, => (suggest folder of related conversation).

if you disable that, does it help?

**Comment by hkclark** [comment]
@opto Thank you for the reply.  I just gave it a try and that setting in the Nostalgy options doesn't seem to make any difference for me (and it turns out it was already unchecked  in my earlier testing).  Let me know if there is anything else I can do to assist on this end.

**Comment by tehcaster** [comment]
Disabling doesn't help for me. I can open the settings later and find it's still/again enabled.

**Comment by hkclark** [comment]
A few things I noticed in doing what troubleshooting I could find:
* I went into the Config Editor and deleted all items with Nostalgy in the name just to be sure it wasn't a bad setting
* If I uninstalled and did a fresh install from https://addons.thunderbird.net/en-US/thunderbird/addon/nostalgy_ng of 3.2.17 then everything is fine.  (I couldn't find 3.2.17 on github... it's like the history of the git repo has been purged.)
* But if I updated to 3.2.18 (that I could find on github) then the issue was present.
* I also used the SysInternals Process Monitor to watch it both with and without the issue.  It's really odd, but it seems to be hammering the Registry much harder under 3.2.18 vs 3.2.17.  However, it's all strange access of Keys that seem really odd... stuff like `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.html` and `HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache` and `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.txt` over and over.  I tried look at the commits to see if anything looked like it might correspond, but with the history removed from the github repo, I couldn't get very far with that.

However, I guess I'll stay at 3.2.17 for now.

**Comment by hkclark** [comment]
@opto I just tried 3.3.2 and I'm not getting the CPU issue.  I'm not sure if logging is the only change between 3.2.17 and 3.3.2, but I seem to be good with 3.3.2.  Thank you!

**Comment by tehcaster** [comment]
> Disabling doesn't help for me. I can open the settings later and find it's still/again enabled.

That was actually because I wasn't clicking OK in the settings dialog, because the button wasn't visible until I manually enlarged the window.

**Comment by opto** [comment]
change between 3.2.17 and 3.3.2: no change in general Nostalgy functions other than disabling the logs.

Extra: the search function with  the browseraction button, but that code is in a separate place and probably does not affect the original Nostalgy functions.

i am closing this for now, you can reopen if needed.

Klaus
