### ISSUE TITLE
Hot keys activate when typing in description in Lightning calendar description field

### ISSUE THREAD

**Issue by bsgcic** [opto/nostalgy-xpi#173]
Thunderbird 91.7.0 (64-bit) on Ubuntu 20.04LTS (all updates applied) Lightning 2.7 Nostalgy ++ 3.3.2.
Hot keys activate when typing in description in Lightning calendar description field.  Effectively need to type the description in a text editor and paste into the calendar event description because of the interference of Nostalgy hotkeys activating when type directly.

**Comment by opto** [comment]
in options, restrict commands to email tabs. Please also try 3.3.17: goto code here on github, choose releases on the right side of the screen

**Comment by bsgcic** [comment]
Restrict commands to email tabs solved it.  Ok, will try out 3.3.17 too. Thanks Opto!
