### ISSUE TITLE
Nostalgy keys not working with TB101b1, TB102

### ISSUE THREAD

**Issue by internationils** [opto/nostalgy-xpi#174]
I just upgraded from TB100b4 (I think, it was the latest 100 series beta) to 101b1 (win 11 64 bit) and nostalgy 3.3.17 stopped working - no response to any keys (at least g, s) . I updated to 3.3.21 and that did not work either. I tried the "deactivate and reactivate addon" trick, but no change.
TB seems to take the key input, "s" stars the current message for example.

**Comment by internationils** [comment]
Just tried with a 102a1 daily, also does not work at all.

**Comment by internationils** [comment]
...actually, Nostalgy is disabled for 102. Can you please make the next version available for 102 (new daily) as well please? I will update manually in the meantime and try again... thanks!

**Comment by internationils** [comment]
Just tested with TB102.0b5, still not working. The Search++ button does not do anything either.

**Comment by jobisoft** [comment]
Can you give this a try for TB102:
[nostalgy++3.5-tb.zip](https://github.com/opto/nostalgy-xpi/files/8980411/nostalgy%2B%2B3.5-tb.zip)

Does that work?

**Comment by internationils** [comment]
@jobisoft seems to work again with 102.0b8 (64-bit) under win11 ... thanks! Both the keys and the search++ seem to work as before.

**Comment by mdonz** [comment]
> Can you give this a try for TB102: [nostalgy++3.5-tb.zip](https://github.com/opto/nostalgy-xpi/files/8980411/nostalgy%2B%2B3.5-tb.zip)
> 
> Does that work?
Wow. That's looking great here on my test set up for TB102! Thank You.

**Comment by internationils** [comment]
Once that 3.5 version from @jobisoft is available this issue can be closed as far as I'm concerned. 

- https://addons.thunderbird.net/en-US/thunderbird/addon/nostalgy_ng/?src=search shows 3.4.2
- https://github.com/opto/nostalgy-xpi/releases releases XPI page 3.3.21 from April
- https://github.com/opto/nostalgy-xpi github code 2.2.4 (2 years old) 
 
would be nice to have a current version in github again. @opto any chance of that?

**Comment by internationils** [comment]
FYI, 3.4.2 (and probably 3.5 as well) is incompatible with TB103beta... need to change the JSON file
