### ISSUE TITLE
How to open a Search++ tab?

### ISSUE THREAD

**Issue by ttamttam** [opto/nostalgy-xpi#176]
It's certainly something obvious… but I could find how to do that.

Best regards

**Comment by ttamttam** [comment]
Well. I eventually found a solution: I added a button in the toolbar for this. Any other solution?

**Comment by opto** [comment]
there should be a so called browseraction button close to the hamburger menu. Its icon is (here on win 11 and Ubuntu 20) a searchglass, followed by a ++.

If you don't have this button visible, please specify your operating system, so I can report to the TB team.

There is still a bug: after a TB restart, if you want to open a new tab for a new directory, you need to close old already open tabs. Within a TB session, there is no problem to open several tabs.

I will put more help into the startup document for next version. The bugfix will come ca. within the next week.

Klaus

**Comment by opto** [comment]
please  rightclick on the toolbar, select customize and see if they can re-add the button (advice from TB team)

if not, it would be a bug

**Comment by ttamttam** [comment]
Oh. My reply to https://github.com/opto/nostalgy-xpi/issues/176#issuecomment-1120779821 by e-mail did not show up here. Sorry for that.

What I wrote was confirmed @opto last comment:

>  Right-clic on the toolbar -> Customize
> 
> and drag'n drop the lens icon (with a "++" label, if I remember correctly) on the toolbar.
> 

Best regards

**Comment by Olifair** [comment]
No, the icon was not visible automatically (windows 10 pro 64 bits; TB 91.9.0 32bits), but I was able to add it easily. Thanks for this wonderful improvement.

**Comment by opto** [comment]
I was told some errors of that are already fixed in 102, so we can only file a bug if it still occurs in a fresh 102 profile

**Comment by ThomasHeinrichSchmidt** [comment]
Using TB  91.9.0 on Windows 10 the Search++ button was displayed by itself:
![Issue176](https://user-images.githubusercontent.com/8068047/167586528-36a76247-8126-4b42-8d9f-2a9f53aacc12.jpg)

**Comment by opto** [comment]
seems I can close this ...
