### ISSUE TITLE
Version 1.0.16 installed but keys are not working?

### ISSUE THREAD

**Issue by mdonz** [opto/nostalgy-xpi#18]
I was so excited about the continuous development and installed the new version (0.394 was running before) but at the moment it looks like none of the keys are working (?).

For a moment I thought the add-on was accidentally disabled but that is not the case.

For keys like "s", the default TB action (to star) is happening.

**Comment by opto** [comment]
try 1.0.16a

**Comment by mdonz** [comment]
Just installed and a first test shows that all functionality is there and all seems "back to normal". I am happy for this to work and excited to see that you have picked up and continue on Alain's work. Thank you.
I should have included the OS that I am using (Ubuntu 18.04) as I realised from #19 .
One minor issue, only for reporting: Under TB's add-ons manager, this version shows itself (wrongly) as 0.394. The initial 1.016 version was showing there correctly.

**Comment by rmmbr** [comment]
> One minor issue, only for reporting: Under TB's add-ons manager, this version shows itself (wrongly) as 0.394. The initial 1.016 version was showing there correctly.

I could not confirm that. First I deinstalled 0.394 and than I installed 1.0.16a. The version number is shown correct in my Add-on-manager. W10 1909 64, TB 68.3.1.

**Comment by Cito** [comment]
The version number 0.394 is in the manifest.json of both 1.0.16 and 1.0.16a.

**Comment by salzrat** [comment]
When double-clicking on Nostalgy in the addons manager, I get 1.0.16a as version number.

**Comment by Cito** [comment]
Hm, it looks like the version is ok in the .xpi file, but not in the downloadable source code (.zip and .tar.gz).

**Comment by mdonz** [comment]
> > One minor issue, only for reporting: Under TB's add-ons manager, this version shows itself (wrongly) as 0.394. The initial 1.016 version was showing there correctly.
> 
> I could not confirm that. First I deinstalled 0.394 and than I installed 1.0.16a. The version number is shown correct in my Add-on-manager. W10 1909 64, TB 68.3.1.

FTR - I did not uninstall former Nostalgy versions (which I expect to be part of my problem). I installed ver 0.394 initially (cannot remember whether I uninstalled Alain's original Nostalgy version before that), then I installed version 1.0.16 (as .xpi) "over the top of the previous ver 0.394" and then I did the same again with version 1.0.16a, installing it over 1.0.16.
I now realise that my TB add-on manager lists two entries for Nostalgy (!), one for the old version 0.394 (green Nostalgy icon, text says it is from Alain Frisch and its URL refers to Alain; ver 0.394, updated 2 Dec 2019) and one (black Nostalgy icon) with the correct details of version (1.0.16a) and date (19 Dec 2019).
So I will uninstall all former and maybe current version(s) and start freshly with Nostalgy and we can out this little issue to rest. Thanks

**Comment by jpschewe** [comment]
I'm seeing this same issue, the keys don't work. I uninstalled both entries for nostalgy, restarted, then installed 1.0.16a and restarted and no keyboard shortcuts. This is Thunderbird 68.2.2 on Linux. I have another Linux system with the same version of Thunderbird and nostalgy and this one works fine. What information would be helpful in debugging this?

**Comment by jpschewe** [comment]
I found the preferences and found that setting the keys changes the characters to capitals and then it works.
