### ISSUE TITLE
Nostalgy prevents TB from closing properly

### ISSUE THREAD

**Issue by hfm158** [opto/nostalgy-xpi#190]
Yesterday I created a fresh profile, and installed one extension after the other into TB 102.3.1. After installing Nostalgy++ I observe a process remaining after TB is closed. This behaviour is not observed after uninstalling Nostalgy++.

**Comment by opto** [comment]
thanks for the info. Which OS?

**Comment by hfm158** [comment]
Sorry, I should have mentioned that. Windows 10, 64 bit, 21H2, build 19044.2075.
A strange effect now after uninstalling Nostalgy++: I start TB with no TB processes running. A process starts and I get the message: Thunderbird wird bereits ausgeführt, reagiert aber nicht. Der offene Thunderbird-Prozess muss beendet werden, um ein neues Fenster zu öffnen.
Only after hitting, ik TB will start.
Would Nostalgy leave something behing in TB's configuration? This only happened after instlling and uninstalling the extension.

**Comment by opto** [comment]
thanks, I will look at that. After deinstall, there should nothing be left.

On the commandline, you can clean TB up by starting like this: thunderbird.exe  -purgecaches

**Comment by hfm158** [comment]
It seems that this behaviour is not strictly related to Nostalgy++. 
I added some other extensions meanwhile, and again I see the same effect. So it may be a native Thunderbird issue. I did not see it until I upgraded to TB 102.x. It is strange since it does not happen always. Some times all process terminate, sometimes one process remains running.
Sorry for bothering you.

**Comment by opto** [comment]
thanks for the info,  Klaus
