### ISSUE TITLE
3.6.5 moves cursor to body of email (from To: box) when forwarding email

### ISSUE THREAD

**Issue by LampyDave** [opto/nostalgy-xpi#193]
Hello there,
Since 3.6.5 when forwarding an email (either with the 'Forward' button or Ctrl-L) the cursor is moved to the body of the forwarded email instead of being in the To: box. This occurs whether or not the 'Always show cc line in compose' is ticked or not.
Reverting to 3.6.3 removes this behaviour (which is the preferred state).
Many thanks, Dave

**Comment by hi5** [comment]
Known issue: See discussion here https://github.com/opto/nostalgy-xpi/issues/187

**Comment by opto** [comment]
please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.6.13

**Comment by LampyDave** [comment]
Yep - issue fixed with v3.6.13. Many thanks.

**Comment by hi5** [comment]
v3.6.13 works for me 👍
