### ISSUE TITLE
When forwarding message, cursor/focus is in message body instead of To: recipient input

### ISSUE THREAD

**Issue by SKova1965** [opto/nostalgy-xpi#195]
TB Version: 102.4.2
Nostalgy Version: 3.6.11

After the latest update to either TB or Nostalgy, the following issue is occurring and if Nostalgy is disabled in the Add-Ons, the problem stops:

**Steps to reproduce:**
Either from the Drop-Down or CTRL-L while on a message, it will start the Forward Message (either Inline or Attachment).

**Actual results:**
The forward is started and the cursor moves to the Message Body, not the To Address as it always has previously.

**Expected results:**
It should have stopped with the cursor in the To Email Address so that the address that you are forwarding to can be entered.

I started a Bugzilla ticket with TB and then found that it was the Add-On.

**Comment by Olifair** [comment]
I have just tested what you describe : either using the button "forward" or CTRL-L to forward a message : in my case the cursor is always in the address field. Using TB 102.4.2 and Nostalgy 3.6.13 (update 9 nov 2022). So either the problem has already been resolved, or it's specific to your system / preferences. 
Cheers

**Comment by SKova1965** [comment]
Did not see that there was a 3.6.13 version and the fix in it was for this. just installed 3.6.13 and it works fine again.
