### ISSUE TITLE
The last version breaks Thunderbird options

### ISSUE THREAD

**Issue by Danamir** [opto/nostalgy-xpi#2]
Hello,

Glad to see someone is working on this marvelous addon. ;)

The last version of the xpi (without the shortcut displays) works well on my Thunderbird, but the new one prevents the option menu of Thunderbird for opening (clicking on the top right button does simply nothing), and the columns display selection are reset each time I deselect a folder and go back to it. ie. if I desselect the "read", "junk status" and add the "size" columns on the inbox folder it works ; but the setting is not stored. If I display another folder the columns are reset to default.

Thanks !

**Comment by gbstan** [comment]
Various issues here too on 68.2.2
Same here. All tabs disappeared. ` doesn't work anymore.

Previous version for 68 was working (with a few less features).

**Comment by hbarel** [comment]
Same here, 68.2.1.

**Comment by opto** [comment]
which OS? works here on Win 10 home on 68.2.1.
I noticed that the old xpi is inside the new xpi. Maybe that creates problems. I will upload corrected version tomorrow.
Klaus

**Comment by gbstan** [comment]
MacOS 10.14.6

**Comment by rweigle** [comment]
I see the same issue: Option Menu doesn't work. The Tabs do work now with the latest version of the XPI. My Platform: MacOS 10.15.1.
Thanks for the work.

**Comment by gbstan** [comment]
The latest version fixes most of the issues. The only one that is still a bit misbehaving is the Nostalgy Preferences -> Rules, which have still some issues.

**Comment by rweigle** [comment]
Indeed. After really making sure I use the latest version (removing nostalgy and adding it again) the Options Menu and the Tabs work for me.

**Comment by Danamir** [comment]
Confirmed, the last version fixes Thunderbird menu and columns.

But I cant find the Nostalgy options in the addons manager. How do you access it ?

**Comment by CaptEpsilon** [comment]
I'm getting "This add-on could not be installed because it is not compatible with Thunderbird 68.2.2". I currently have v.3 running. Windows 10

**Comment by opto** [comment]
options are in extra-> nostalgy. Not up to current conventions, just as it was originally.

Not all under options is working, just the most necessary stuff.

@CaptEpsilon: do you have 0.393?

**Comment by opto** [comment]
I never yet tested all the checkboxes on the third option tab

**Comment by CaptEpsilon** [comment]
@opto I downloaded 0.393 I believe. That's the one that won't install. I have 0.3 installed already.

**Comment by Danamir** [comment]
> options are in extra-> nostalgy. Not up to current conventions, just as it was originally.

Ok got it ! It is also in the "old" menu bar, in the "Tools" menu.

**Comment by CaptEpsilon** [comment]
@opto Never mind. It appears that I had a corrupted download. Deleted it and the downloaded again and I was able to install and run it. Thanks.

**Comment by opto** [comment]
ok in 0.393
