### ISSUE TITLE
Slow opening of suggestions

### ISSUE THREAD

**Issue by salzrat** [opto/nostalgy-xpi#20]
When I press "s" to move an email, and start typing, after pressing one key, I can often see the list being filled with the matching suggestions at a quite slow pace (it's like an animation). This is a bit annoying and didn't happen in old nostalgy/thunderbird... Not sure whether you can easily reproduce this...

**Comment by opto** [comment]
on win 10 home that does not happen. maybe your processor is busy with other stuff (check taskanager)? Or priority for TB is low?

**Comment by salzrat** [comment]
No, the CPU is otherwise quite idle. It only spikes when I press a key where it finds many matches in the folder structure (note that I have many folders). I verified with process hacker 2 that the spikes come from thundebird exactly after the key presses, so collecting the folders seems to take a disproportionate amount of CPU. I don't think that happened with the previous nostalgy. But it's not a blocking issue, I'm very happy that nostaly works at all! If I can contribute any more to finding the cause of this, let me know.

**Comment by suskozaver** [comment]
Could you define "many folders"?

**Comment by opto** [comment]
collecting the folders is done by TB' s autocompleteservice, so we cannot do anything about that

**Comment by salzrat** [comment]
Maybe it’s just a ui issue - in the previous version, all suggestions opened at once. In this version, it seems as of the box is filled up with suggestions one by one, rerendering the whole box each time, which makes it seem sluggish... maybe the rerendering is the problem, not the collection of suggestions?

**Comment by opto** [comment]
but that is also an TB internal - a textbox with autocompleteservice is used, and searching, collecting and displaying searchresults is done by TB, not by nostalgy

**Comment by salzrat** [comment]
could you point me to the right location in the code where this is happening? Maybe I get an idea from looking at it...

**Comment by opto** [comment]
please try 2.2.2 from ATN for TB78. Still happening? wontfix for TB 68.
