### ISSUE TITLE
Strange Short Cut behaviors 4.0.2

### ISSUE THREAD

**Issue by szmontsaroff** [opto/nostalgy-xpi#211]
1. When entering a short cut to move, after hitting return in the box with the path, the return is passed on to Thunderbird, and all emails open.
2. When typing a short cut in a non email window (such as the calendar or the contact), typing s,c,,g,e activates nostalgy.

**Comment by Remiol** [comment]
Same here

**Comment by opto** [comment]
the latter can be switched off in an option: restrict to mail window (or similiar text)

for the first, which OS?

**Comment by opto** [comment]
For the first, it needs tab or select the folder with Up down Keys.
Will be resolved later
