### ISSUE TITLE
Saving message not working

### ISSUE THREAD

**Issue by chconnor** [opto/nostalgy-xpi#214]
Hi --v4.0.2 on TB 115.3.1 on Kubuntu 23.04 -- I have remapped "x" to save message; it finds the folder I want to save to just fine, and I hit enter, but nothing happens to the message -- it remains where it was.

In the console I see 

```
doCammand  NostalgyMoveToFolder 
XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), URI: Getter, name: Getter & Setter, prettyName: Getter & Setter, abbreviatedName: Getter, setPrettyNameFromOriginal: setPrettyNameFromOriginal(), parent: Getter & Setter, messages: Getter, Init: Init(), startFolderLoading: startFolderLoading(), … }
```

...so it seems that it is at least making the attempt. There are no errors or warnings or other relevant log lines that i see.

**Comment by chconnor** [comment]
Hmm, further details -- saving works from most of my folders, but not my main folder. I have four accounts and switch between them using quickfolders. The 2nd, 3rd, and 4th inbox all work fine when I save, but when I'm on the 1st inbox, it does not work. (Console log looks the same in both cases, but I might have missed something subtle.)

**Comment by chconnor** [comment]
Some folks echoing similar things here: https://github.com/opto/nostalgy-xpi/issues/215

**Comment by chconnor** [comment]
Hmm, even further details -- suddenly it's working for no apparent reason... nothing has changed so I'm not sure why...

**Comment by opto** [comment]
what happens if you deactivate quickfolders? Both use legacy code and might influence each other

**Comment by chconnor** [comment]
I will check the next time it is not working and report back, thanks...

**Comment by opto** [comment]
I think this can be closed due to the new versions
