### ISSUE TITLE
Version 1.0.16a doesn't work properly on Ubuntu Mate 19.10

### ISSUE THREAD

**Issue by rogerval** [opto/nostalgy-xpi#22]
(Apologies for the long post...)
Sorry to be the fly in the ointment, but...
On TB 68.2.2 under Ubuntu Mate 19.10 and with Nostalgy 1.0.16a I'm still having issues.
Pressing s toggles the star on that message, rather than activating Nostalgy "move message".
Pressing c brings up a "mark messages as read by date" dialog, rather than activating Nostalgy "copy message".
Pressing g or G does nothing.
(I should add that I've used previous versions of Nostalgy under Windows 7 with great success.)
Perhaps this is an issue with Ubuntu Mate 19.10? Hard to say.
(I note that it reportedly works under Ubuntu 18.04, but of course a lot has changed between that and the "flavour" of Ubuntu I'm using.)
I'd temporarily edit the Thunderbird keyboard shortcuts so s and c aren't used just for an experiment, but the two addons Mozilla themselves have previously suggested to achieve this are themselves unable to work with TB 68.
(Thunderbird support article here: https://support.mozilla.org/en-US/kb/keyboard-shortcuts#w_customize-or-disable-keyboard-shortcuts )
I'm also aware of the userChromeJS extension but using that to change keyboard shortcuts requires a fair bit of javascript knowledge, which I don't possess at this stage. :-)

Any suggestions (maybe I've missed something obvious :-) ) are welcome.

Once again, thanks for your hard work, it's greatly appreciated. :-)
Roger V.

**Comment by rogerval** [comment]
After writing the above, I tried again, this time heading for the Nostalgy preferences form to pick keys which probably weren't used for anything else.
Changed s for u (which appeared on the Nostalgy form as U not u for some reason...) and tried to save a message, and it worked.
I then changed the key back to s (which appeared as S, not s) and Nostalgy worked with s for save message.
Trying c for copy (without attempting to change it) brought up a "mark messages as read by date" dialog, as noted earlier.
Opening the Nostalgy preferences form, and re-typing c for copy (which appeared as C not c, like before) and saving this preference form enabled the press c for copy to work.
Uninstalling Nostalgy and re-installing it just to double check that I wasn't imagining things did not go back to the incorrect behaviour I commented on earlier. (Where could it put it's preferences in the Thunderbird profile, aside from /home/roger/.thunderbird/<my profile name>/extensions , because it isn't there. :-) )
Baffled I am.
Roger V. :-)

**Comment by drewp** [comment]
Same worked here (change each letter to itself). Ubuntu 19.10 with a custom fvwm desktop. Maybe rogerval and I had the same leftover nostalgy prefs or something.

**Comment by rogerval** [comment]
Thanks for the confirmation, I was wondering if I was imagining things :-)

**Comment by krouskop** [comment]
On a brand new install of Ubuntu Mate 18.04.03, with a brand new install of Thunderbird 68.2.2, with a brand new Thunderbird profile -- upon installing Nostalgy version 1.0.16a, I ran into the same thing ('s' star-ing, 'g' doing nothing).

Going to Tools > nostalgy, changing the keyboard shortcuts to 'disabled', and then setting them back up to the expected keys did the trick for me. Thanks for the hints from this issue report's threads above!

**Comment by mako-git** [comment]
I experienced the same for linux mint 19: the keybindings did not work properly after installing the addon, but resetting them to the same values solved the issue. 

Maybe a useful piece of information for bugtracking: In the faulty initial configuration, the keys are all lowercase, ('s' for Save, 'c' for Copy, etc.). Resetting them by typing in a lowercase 's', 'c', etc., the displayed keybinding changes to an uppercase 'S', 'C', respectively. Despite the uppercase 'S' being displayed in the preferences, the actual keybinding still reacts to hitting the lowercase 's' key. Uppercase keybindings (like the one for Save as suggested) are displayed as 'shift S'.

**Comment by laram1989** [comment]
So glad you made this available for Thunderbird 68, thank you so much!

Works like a charm, but a very slight annoyance is that whenever I start Thunderbird the Nostalgy text input field at the bottom of the Thunderbird window is showing for some reason. I can make it go away by simply hitting Escape, but I don't remember the text input field being there previously?

Happening on Linux Mint 19, Thunderbird 68.4.1.

**Comment by opto** [comment]
please try 2.2.2 from ATN for TB 78. Still happening?
