### ISSUE TITLE
4.0.5: Cannot use Nostalgy when email is "open" in a tab and takes extra keystrokes once I close it

### ISSUE THREAD

**Issue by hkclark** [opto/nostalgy-xpi#224]
I normally keep the "Messages Pane" (F8) closed and hit Enter on each message to open it and read it using the full size of the overall Thunderbird window.  Before TB 115 I could use Nostalgy to move the message while the message was open (it would close the message and do the move, returning me to whatever folder I was in when I opened it).  With TB 155 and any of the 4.0.X Nostalgy++ versions, I see the Nostalgy icon (two boxes and the curved arrow) down in the lower right of the status bar (and if I hover over the icon, it mention the Nostalgy keyboard shortcuts I have configured), but none of the shortcuts do anything and it never shows  "[+ Shift => SomeFolderHere]".  

To move the message I have to:
1) Close the email (e.g., Ctrl+W) and return back to whatever folder I opened the message from
  * Note: At this point I still see the Nostalgy icon in the lower right on the status bar, but none of the keyboard shortcuts work and there is no "[+ Shift => SomeFolderHere]" either.  It just like when I had the message open.  To get the keyboard shortcuts to work and to get the "[+ Shift => SomeFolderHere]" back for this message I have to do steps # 2 and # 3 below.
2) Hit the up or down key to move to a different message
3) Hit the opposite down or up key to move back to the original message
4) Now the "[+ Shift => SomeFolderHere]" and the keyboard shortcuts work.

I have tried disabling all other Addons and it doesn't seem to change the behavior I'm getting.  I have noticed this across all of the TB 115.X.X and Nostalgy 4.0.X versions, but currently I'm on TB 115.3.2 and Nostalgy 4.0.5.

Thank you very much!

**Comment by opto** [comment]
yes, operation in message pane/window has not been reactivated yet, will follow

**Comment by hkclark** [comment]
@opto OK, great.  Thank you for letting me know it's on the list!

**Comment by opto** [comment]
it works in the 3pane with message always open .I didn t try closed then open with F8. Maybe the Statusbar then has items with other id than what we use for insertbefore, and Part gets left off or are not activated.

Also, pure messagewindow is on the way but not Finished yet. there are just so many functions that disappeared and which are now in a different class with a totally different Name.

like the function to Focus the next message after delete or move. obviously tb still does that, but it is a good example for something now hidden somewhere. no big Deal, but there are millions disappeared functions.

**Comment by opto** [comment]
ok, so when we are in the mainwindow, but not in mail:3pane, but in a tab with type messageDisplay ... then we need the Nostalgy commands.

so yes, this will be coming

**Comment by opto** [comment]
this is working now and a test version will come later today

**Comment by opto** [comment]
https://github.com/opto/nostalgy-xpi/releases/tag/v4.0.6

**Comment by hkclark** [comment]
@opto Initial testing on my end looks great!  Thank you!  I'll leave this open for another day to maybe get input from others, but I'll make a note to close it tomorrow (in ~24 hours) if nobody has uncovered any issues.  Thanks again.

**Comment by hkclark** [comment]
@opto I have not noticed any issues at all with this and since we haven't heard of issues with anyone else, let's close this.  Great work fixing this!!
