### ISSUE TITLE
Where are latest versions of nostalgy?

### ISSUE THREAD

**Issue by cjholly** [opto/nostalgy-xpi#25]
Sorry to post this kind of query. The latest version of opto's nostalgy-xpi seems to be 1.0.16, but somehow I found 1.0.25 and others in between. Now I cannot find any of them. Can someone post where they are hiding from me?  --Chris

**Comment by boutilpj** [comment]
https://github.com/opto/nostalgy/releases

**Comment by opto** [comment]
it is a bit hidden.
If you click on code, the line below has an entry releases. Or look here: https://github.com/opto/nostalgy-xpi/releases

**Comment by opto** [comment]
the current version 2.2.2 is at addons.thunderbird.net
