### ISSUE TITLE
Save to newly created IMAP folder fails

### ISSUE THREAD

**Issue by sphh** [opto/nostalgy-xpi#255]
I want to save a message to an IMAP folder, which does not exist yet:
1. I press `s` to save.
2. I enter the new IMAP folder and press `Enter`.
3. I confirm the creation of the new IMAP folder.
4. I get an error message telling me that that folder does not exist.
5. After confirmation I press `s` again.
6. I enter the same IMAP folder from 2.
7. The message gets saved into the IMAP folder created in step 2./3.

I would expect that the message is saved immediately after the new IMAP folder has been created.

I observed this behaviour now for a very, very long time, so it is not new the the latest versions, which are:
Manage Email/Nostalgy++: 4.1.4
Thunderbird: 115.7.0

**Comment by mdonz** [comment]
I have never used that feature before to create a new folder that way. I usually create a new folder first with the standard Thunderbird commands and then start using it with Nostalgy. My shortcut to save an email to a folder is "r" due to "s" being predefined by Thunderbird on an English installation.
However, here on Ubuntu, TB115.7.0, Nostalgy 4.1.4, the steps all work as expected. With a first save command to a non-existing folder (test2 chosen as folder name), a dialogue opens to ask "Create new folder [test2] under <account name>". I can confirm with OK and (a) new folder "test2" will be created and (b) email will be moved (saved) in that new folder.

**Comment by Olifair** [comment]
I have never created a new folder in the IMAP this way, but I do it regularly for local folder and it works as expected : using "S", the new folder is created and at the same time the message is moved. So this is perhaps a problem with creating the folder on the server, it perhaps takes more time and thus the message cannot be moved instantly ?

**Comment by sphh** [comment]
That is also my inkling: The creation of the folder on the server takes too long and hence the subsequent moving of the message fails!

I have no idea, how this is implemented, but if it were possible for Nostalgy to wait for the creation command to finish (either successfully or with a failure), that problem would be solved …

**Comment by opto** [comment]
... => feature request: user selectable delay between creating folder and moving message

(here, it works as well, but my imap server is in tthe same local network)

**Comment by sphh** [comment]
If the IMAP server does not report back the successful creation of the new folder, it might be worthwhile to let Nostalgy try to move the message several time (configurable) with a (configurable) delay between the tries.

My IMAP server is accessed over a slow (mobile) network and might not be the quickest itself.

**Comment by mdonz** [comment]
I experience similar between an account on a local imap server (fast access = folder creation working as expected) and an account on a remotely hosted imap server (mailcow.de) which fails (but creates the folder hence needs a second attempt to save, exactly as the original report states)

**Comment by opto** [comment]
it seems that the new webextension side waits for the folder to exist, please try this:
https://github.com/opto/nostalgy-xpi/releases/tag/v4.1.5

**Comment by mdonz** [comment]
Oh, yes. Test on my (slow) remotely hosted imap server which failed in the past are now looking good! Great.

**Comment by sphh** [comment]
Many, many thanks, @opto!
That works great. I can now save a message to a newly created folder on my (slow) IMAP server in one single step. Well done.
