### ISSUE TITLE
Is Nostagly stable with TB 115 now?

### ISSUE THREAD

**Issue by JeffFessler** [opto/nostalgy-xpi#257]
At the top of the add-on page here
https://addons.thunderbird.net/en-us/thunderbird/addon/nostalgy_ng/
it says "Works with Thunderbird 115.0 - "

But below the "About this Add-on" on the same page it says
"The version for TB 115 is in review"

The "in review" makes me think it is still being beta tested or such?
I am waiting to install TB 115 until Nostalgy++ is stable because it is essential for me!

Thanks!

**Comment by opto** [comment]
Forgot to adapt the text ... we have had several versions since ca. September 2023

some minor feature may not work yet, but overall, it is complete. And if I read here which sub-feature is needed, I can bring that back. Like the search++ is not there yet, that is a major efford.
