### ISSUE TITLE
Move messages type in field not available

### ISSUE THREAD

**Issue by MartinChristoph** [opto/nostalgy-xpi#26]
Hello Klaus
Thank you for your message.
Well few years ago I had installed this add on on previous versions of TB and I did love it.
I just could select "move to" then" type in field was visible, once starting typeing the choice of folders was narrowing. Based on this add on I created a folder system which works great.

Once updated to 68 and installed nostalgy I can't see this option. For instance when right click on a message, then "move to" there's only TB default system of choices e.g. recent. No field where I can type folder name.
With my folder system moving messages in regular way is not an option.
Maybe I do something wrong ( I hope - so there's an easy solution)
I'd apprecaiate so much your assistance to solve this problem.
Regards.
Martin

**Comment by opto** [comment]
some of the original letter (like s) are in conflict with TB's shortcuts (S= set star).

The first try is to eiher set another letter or to reset the current letter. For many, that was sufficient. Go into the options where you can set the keys and preferably use some that are not used by TB or OS. Test: open message list, highlight an unimportant message (in case you have a shortcut for delete), type a few letters and observe which do nothing. Use those for nostalgy++.

Please let me know if that helps.

Klaus

**Comment by MartinChristoph** [comment]
Dear Klaus

Thank you for your message.
I managed to run and do some tests. Works OK.

There's one issue. For some reasons from time to time Nostalgy++ moves 
messages to archives folder instead to a folder of choice.

Regards

Martin






W dniu 30-04-2020 o 11:06, opto pisze:
