### ISSUE TITLE
Upgrade to  Thunderbird 78.xx /old version can't work in 78

### ISSUE THREAD

**Issue by dessertrain** [opto/nostalgy-xpi#27]
Hello,
with the release of Thunderbird 78.xx the addon does not work anymore. The installation works, but there is no possibility to change the settings in the menu.   

Is there hope that you can get it running again?

Tom

**Comment by opto** [comment]
yes, it is nearly finished. Just give me a week or 10 days. Settings and moving/copying is working here, already

**Comment by suskozaver** [comment]
@opto too early to ask how's it going? 😊

**Comment by Izwbusr** [comment]
@opto can you please comment on what the expected delivery date is for the Thunderbird 78 version?  You had recently said you expected it to be finalized about 10 days ago.

Thanks!

**Comment by cpriest** [comment]
Just wanted to leave a comment and thank you for your work in re-writing/porting this for the newer TB model.  I did the same for an XPI based extension for FF a long while ago (Snap Links Plus).

Can I help with anything?

**Comment by bill-mcgonigle** [comment]
Hey, @opto, what do you think about committing on a branch, so we can maybe give a hand where needed?

**Comment by Olifair** [comment]
Hello @opto , don't know if you follow [this thread](https://github.com/nostalgy/nostalgy/issues/85), but there seems to be now a 1000 Dollar bounty for the development of Nostalgy

**Comment by PresGas** [comment]
Sounds like @opto should collect!  :grinning:

**Comment by rhorbas** [comment]
@PresGas Almost! :-)
This is a pretty serious bug:
https://github.com/nostalgy/nostalgy/issues/85#issuecomment-723981524

>  the key "c", when writing e-mails, lets the focus jump into the cc recipient field. (Thunderbird 78.4.1)
> As far as I can see, there is no such keyboard shortcut in nostalgy, but when I deactivate the addon and restart, the behaviour is gone.

**Comment by opto** [comment]
see issue #29
