### ISSUE TITLE
Detail-view for email: No move/copy-hotkeys

### ISSUE THREAD

**Issue by neufeind** [opto/nostalgy-xpi#3]
In the detail-view of an email we previously also had the hotkey to move that email. Currently you have to leave the email to move it from the list-view - which works for the moment.

**Comment by mdonz** [comment]
Does this issue still exist in latest version 0.394? I started with using 0.394 and it appears I do not have this issue here?

**Comment by neufeind** [comment]
When I open a message still nothing happens when I press "s" to move the message somewhere, no folder-selection. So yes, for me this is still current.

**Comment by opto** [comment]
is your message in a tab or in a window?

**Comment by neufeind** [comment]
Ah I see, that makes a difference. Tab works, new window does not.

**Comment by opto** [comment]
solved, will upload today
