### ISSUE TITLE
Compose dialog -> autocomple address unusable (1 char per second)

### ISSUE THREAD

**Issue by lemeur** [opto/nostalgy-xpi#33]
With the latest version of the plugin, when composing an email an trying to enter a destination address, each char takes 1 sec to be displayed.
This might be due to the interaction with the autosearch in LDAP directories or Exchange directories.

Disabling Nostalgy++ fixes the bug.

**Comment by opto** [comment]
did you try 2.2.2?

**Comment by lemeur** [comment]
Yes, the installed version is 2.2.2

**Comment by opto** [comment]
thanks, which OS?

**Comment by lemeur** [comment]
MacOS 10.15.6
Thunderbird: 78.4.1 (I'll try 78.4.2 asap)

**Comment by lemeur** [comment]
This is fixed with Thunderbird 78.4.2. I close the ticket.
Thanks for the support.
