### ISSUE TITLE
Problem exporting rules

### ISSUE THREAD

**Issue by maherma-adg** [opto/nostalgy-xpi#34]
There are problems with rule export, a popup with JSON content is shown, but it's too big and gone out of screen to see it complete

Trying to cut and paste content show a truncate JSON.

Tested on TB 83.0b2 (MacOS 10.15.7)

![image](https://user-images.githubusercontent.com/6205177/98645504-5f59f500-2332-11eb-839f-e75532ad7f53.png)

**Comment by opto** [comment]
the rules are copied into a javascript alert box, no changes to earlier code.
Apparently, this alert box in TB 78 works different from 68.

I will change that to either copy into clipboard or write a file, whatever is easier (can TB clipboard accept long strings?)

Klaus

**Comment by opto** [comment]
this now goes directly into clipboard
