### ISSUE TITLE
Foldernames with plus-sign not selectable

### ISSUE THREAD

**Issue by neufeind** [opto/nostalgy-xpi#44]
For historic reasons I have some IMAP-folders with a plus-sign ("+") in it's name. Moving to those folders worked fine in the past. I can search for those folder and get suggestions. But selecting them does not work to move a message. But manually going into that folder-name and escaping the plus with a backslash seems to work.

**Comment by opto** [comment]
if I create a new folder with name: 'subtest+new', then it works. The question may be how your imap server escapes the plus?

**Comment by opto** [comment]
(also on imap with hmailserver)

**Comment by opto** [comment]
just retested: it definitely works here. I cannot search for + only, there, I also would need \+.
But if I have part of the subfolder name, it finds subtest+new and can move the email there.
It would not be too difficult to have a general replace of + by \+ after the folder is selected, or on input of +.

I am not sure that should go into the addon, but if you can do some programming (or zipping/unzipping files), I can tell what you need to do.

Klaus

**Comment by neufeind** [comment]
Thanks a lot for testing and your quick response.

I had the issue with a Zimbra-server (not sure exactly what they use for IMAP). Worked fine for me on another server running dovecot. I now renamed the folder and renamed it back - works with plus now as well. What worried me was it showed the foldername correct, but didn't allow to select it then.

Testing it further: One more thing about the plus is that if you have a folder "abc+def" and type "abc" it shows up in the list with "abc" marked. If you add a plus it shows "abc+" marked. If you add a "d" it does not show "abc+d" marked but that folder is gone from the list. Is that something special about the plus you can reproduce maybe? Other than that I think should close this plus-issue here for the moment.

**Comment by opto** [comment]
https://github.com/opto/nostalgy-xpi/releases

Nostalgy++ 2.2.3 with new features

@opto opto released this now

This release has some new features:

    Esc-r shows/opens the attachment list of a message. Esc-1 (-2, -3 etc.) displays the first, second ... image attachment. No longer do we need to open an external image viewer to have a preview of Photo/image attachments.

    The width of the folderbox in characters can be set in a pref.

    The help text in statusbar has been put into a tooltip to give more space for long foldernames.

**Comment by neufeind** [comment]
No change here with 2.2.3, as far as I can see.

**Comment by opto** [comment]
ah, now I see. yes, a new issue would be good, as + seems to work in general.

I didn't see this second part of your request and thought it to be finished ...

**Comment by neufeind** [comment]
Thanks. That part is split off into #59 now, closing this one here.
