### ISSUE TITLE
[Request] Show Version somewhere

### ISSUE THREAD

**Issue by EricEffern** [opto/nostalgy-xpi#58]
Hi opto,
would it be possible to show the actual version (e.g. 2.2.3) somwhere ?

**Comment by opto** [comment]
I think it is in the upgrade/install popup, and  in the addons tab. (tools->addons), click on addon name.
I could put it into the help popup as well.

**Comment by EricEffern** [comment]
You are right, its in the tools->addon, klick on addon name, then scroll down. Solved, thanks a lot !

**Comment by EricEffern** [comment]
You are right, its in the tools->addon, klick on addon name, then scroll down. Solved, thanks a lot !
