### ISSUE TITLE
Mouse clicks not executed in folder selection

### ISSUE THREAD

**Issue by internationils** [opto/nostalgy-xpi#6]
When selecting a folder (with g,s,m ...) I get a list of folders. I can mouse over them to highlight them, but clicking does nothing. Enter then selects the highlighted folder.
This is on Ubuntu Eoan, TB 68.1.2, Nostalgy XPI .393
Thanks for your work on this!

**Comment by EricEffern** [comment]
Same for me on Win7 / Win10

**Comment by opto** [comment]
win: this works on rules: mouseclick enters folder into edit field.

Same for s,g,m, but Enter writes 'Enter' instead of doing the action

**Comment by opto** [comment]
seems to work now

**Comment by internationils** [comment]
Now at TB115 and N4.0.5 so closing this
