### ISSUE TITLE
TB windows increases width over the right screen edge when nostalgy is invoked

### ISSUE THREAD

**Issue by ThomGr** [opto/nostalgy-xpi#66]
When putting TB on the right half of the screen with WIN-RightArrow (so it is flush with the right screen edge) and invoking nostalgy by "s" often causes the TB window to be come a few 10 pixels wider beyond the screen edge. In the screenshot, I just pressed "s" and you see the right hand side of the window disappers. I had hoped this was fixed in 2.2.4 (#37 ), but this does not seem to be the case.

![grafik](https://user-images.githubusercontent.com/27725313/101184242-c7a9a700-3650-11eb-94fb-c16a74931717.png)

(I know I could have faked the screenshot, this is just to show that the folder names are way to short to cause this imho)

**Comment by PresGas** [comment]
This is likely a duplicate of this:

https://github.com/opto/nostalgy-xpi/issues/37

**Comment by ThomGr** [comment]
No dup of #37 as that one is resolved, but this one not. Used 2.2.4

**Comment by ThomGr** [comment]
hmm, strangely it seems that the update to 2.2.4 was not complete, although I explicitly updated. Anyway, solved now.
