### ISSUE TITLE
0.394 will not install on TB 68.2.2

### ISSUE THREAD

**Issue by aeromorrison** [opto/nostalgy-xpi#7]
There is an error message when installing from file that says it is not compatible with TB 68.2.2.

**Comment by opto** [comment]
it does here on Win 10. Maybe redownload?

**Comment by aeromorrison** [comment]
I had 0.393 installed prior. It was working fine. However, Thunderbird updated and then I removed 0.393 prior to trying 0.394 and it wouldn't work. I then tried to go back to 0.393 and it will not install now either on TB 68.2.2.

I've re-downloaded Nostalgy several times and been through a reboot and restart of TB, but I still get the same issue.

Here is a screen shot of the error box that pops up.
![image](https://user-images.githubusercontent.com/7440842/69572144-7e307180-0f91-11ea-8ad5-3f3bcedacf00.png)

**Comment by opto** [comment]
which OS? Several others were successful on win10.

**Comment by jdbonjour** [comment]
Not compatible with Thunderbird 68.2.1 on Ubuntu 18.04.3 LTS

**Comment by opto** [comment]
Never had that. Several others report that it is ok on Win10.

Can you try in a fresh install of 68.2.2 with a new profile?

**Comment by aeromorrison** [comment]
I'm not in a position to try it on a fresh TB install at the moment. I have quite a few email accounts and setting that will need to be reconfigured with a totally new profile. However, I may get a chance to try that on Friday.

**Comment by opto** [comment]
the idea is not to put your old email into the profile. rater, just use an empty profile, install nostalgy and see whether that works. Something in your old profile could make a problem.
You need to install a TB into a different directory (!!!) and start a new empty profile. I think you can even cancel account configuration, addons can be installed even if no account is set.

**Comment by mdonz** [comment]
I am new here and as a fan of Nostalgy, I am excited to read that there might be a future for the add-on! Thanks so much to @opto for the work yet.
I am using Thunderbird on Ubuntu 18.04 LTS, using only the packaged versions coming through the Ubuntu update channel. Today was the day to finally see the update to TB 68.2.1. That's the version that TB states under its Help (I thought I had seen somewhere else version 68.2.2 but that might be wrong, cannot find evidence).
I have uninstalled the previous, original version of Nostalgy, download from here and tried to install Nostalgy 0.394 but I ended immediately where @aeromorrison had the issue. Same error message but in the message it also refers to TB 68.2.1 version (version consistent = good) .
I then created a new TB profile via ProfileManager and tried to install the add-on there but immediately hit the same error

**Comment by PresGas** [comment]
Same situation as @mdonz here... Xubuntu 19.10

**Comment by mdonz** [comment]
As an update to my previous post, what I am trying now seems to indicate that the file that I downloaded might be damaged (?).
To open a .xpi file, in the past you had to rename the file extension to be .zip and then you could open this with open with a compression utility i.e. Winzip for the Windows world or "archive manager" for us Linux users. This does not work with the downloaded nostalgy.zip (an error occurred while loading the archive).
I was wondering whether even the .xpi file structure might have changed but downloading some other, recent .xpi files manually (i.e. the latest Lightning version for TB 68), these .xpi file open as usual after renaming to ".zip". ANy other download location that we can try please?
Thanks, Michael

**Comment by mdonz** [comment]
Just to confirm, I have downloaded nostalgy.xpi now again and this time the resulting file is smaller than the last download and it is installing! hope that helps others here like @PresGas

**Comment by PresGas** [comment]
Okay, I think I see the issue here! When you are at this page:
https://github.com/opto/nostalgy-xpi
...and you right click to save the file there it shows up as a file of:
`nostalgy.xpi: HTML document, UTF-8 Unicode text, with very long lines`
However, when you go to this page:
https://github.com/opto/nostalgy-xpi/blob/master/nostalgy.xpi
...and download from there, we get the correct file and it installs properly:
`nostalgy.xpi: Zip archive data, at least v2.0 to extract`

I will be playing around with this, but am very pleased to have someone taking up this mantle!!

**Comment by mdonz** [comment]
> Okay, I think I see the issue here! When you are at this page:
> https://github.com/opto/nostalgy-xpi
> ...and you right click to save the file there it shows up as a file of:
> `nostalgy.xpi: HTML document, UTF-8 Unicode text, with very long lines`

Ah, now I understand it finally. Rather a right click on that above URL, you left click on "nostalgy-xpi   with version number") and then you come to the correct download link where it says 38KB.

Maybe we are just not Github savvy enough? ;-)  

Anyway, I am pleased to have the core functionality back, the most important features for me from the former Nostalgy. So thanks again to @opto for your work. 

I will continue to be involved, trying to help at least with feedback and bug reporting.

**Comment by PresGas** [comment]
@mdonz I am semi-savy (I ran a github:enterprise instance on prem at a job), and will admit this has not typically been the way to "release" software. @opto may actually want to push releases off of the fork and not in this project?

https://help.github.com/en/github/administering-a-repository/creating-releases

If one looks at that doc, it shows how to upload those xpi files.

**Comment by Cito** [comment]
Yes, the release should not be done via an additional repository (opto/nostalgy-xpi), but using the releases feature in the same repository (opto/nostalgy).

**Comment by aeromorrison** [comment]
OK. I've tried the alternate process above and it appeared to work. There are definitely some odd nuances with this workflow.

**Comment by PresGas** [comment]
@aeromorrison , yeah. Once we get @opto set for the new workflow with releases it should be much better.

**Comment by RobertKorteweg** [comment]
@PresGas thank u for the comment a few days ago, i also had downloaded the wrong file, it now installs on TB68.2.1 (Linux Mint 19 Tara).

My previous rules are all back, but i can't seem to find the rules window to change them, Nostalgy does nog show op in de add-ons submenu. I will do some more seaching or open an new issue.

**Comment by opto** [comment]
please try .0.16a

**Comment by opto** [comment]
the new version for 78 should fix this, but please wait until I have uploaded the fix for #29

**Comment by opto** [comment]
please try 2.2.2 at ATN
