### ISSUE TITLE
Backspace/ESC are added literally to the filter string after TAB an not match

### ISSUE THREAD

**Issue by ThomGr** [opto/nostalgy-xpi#71]
When using nostalgy with "s", and typing a string that does not match any folder, and hitting TAB: any subsequent ESC or backspace is taken literally and added to the search string. 
![grafik](https://user-images.githubusercontent.com/27725313/101880804-cbc74e80-3b93-11eb-8182-846411f2084f.png)

When putting the cursor into the edit field again the keys work again as expected.

**Comment by hi5** [comment]
I've noticed this as well.

**Comment by opto** [comment]
so the tab makes the box loose focus, and then we do not catch the escape.

What you see is standard TB input box behaviour. Boxes are no longer closed by esc, we need to add that functionality and also need to make sure that not all esc buttons in TB are blocked

**Comment by opto** [comment]
resolved
