### ISSUE TITLE
categories/labels/tags?

### ISSUE THREAD

**Issue by r2evans** [opto/nostalgy-xpi#74]
opto, thanks for the updated Nostalgy.

Is there an intention of porting the quick-tagging (labels, categories, tags, whatever) emails?
(Is there a roadmap where this question would have been preempted? Apologies if there is.)

**Comment by opto** [comment]
not sure what you mean. Or rather, if this is what original nostalgy did on tags, that was working ....
maybe some update within 78 killed it off?

**Comment by r2evans** [comment]
I'm

**Comment by r2evans** [comment]
I'm embarrassed to say that all of the discussion months and months ago did not support (in my head) the readiness of quick-tags, and one or two questions/comments about them went unresolved. Since this use is really my primary motivation (and I am an addon-minimalist), I did not test sufficiently and my muscle-memory from TB-60* days failed me. My apologies, opto, it's there.
