### ISSUE TITLE
Empty text field has keyboard focus after TB is started

### ISSUE THREAD

**Issue by jbouttier** [opto/nostalgy-xpi#8]
Hi,

I am using version 0.394 on Thunderbird 68.2.2/macOS 10.15.1. Immediately after starting Thunderbird, there is an empty text field appearing under the status bar. This text field has the keyboard focus as the characters I type appear there (see screenshot), but nothing happens. I need to click with the mouse elsewhere (e.g. on the message list), then this text field disappears, and only then I can use the keyboard normally (N to see the next under message, G/S/C Nostalgy keys, etc). This text field seems different from the folder autocompletion field, which in my setup just replaces the status bar, instead of appearing below.
Best,

  Jérémie

<img width="273" alt="Capture d’écran 2019-11-27 à 14 02 42" src="https://user-images.githubusercontent.com/18415008/69725556-bfa25780-111e-11ea-94ea-bc5047d6f69a.png">

**Comment by opto** [comment]
solved, will upload today can't try on mac
