### ISSUE TITLE
Cannot install in 78.6.0 Linux

### ISSUE THREAD

**Issue by lingfish** [opto/nostalgy-xpi#82]
Hi, seems the latest from addons is not compatible?

**Comment by Olifair** [comment]
I'm running (that is, have been regularly updating to) TB 78.7.0 (32 bits), and have no problem running Nostalgy++ V 2.2.4

**Comment by mdonz** [comment]
Nostalgy++ v 2.2.4 is running fine here in Thunderbird v 78.7.0 (64bit) Linux (Ubuntu) as well. However, this is an upgraded TB version whereas the original post indicates a problem with a fresh install of Nostalgy++ on that TB version (?). Have not tried such a fresh install here.

**Comment by opto** [comment]
I am new to Linux and am testing it in a Linux distro installed upon Android: userland + Kali Linux.

TB installs fine, Nostalgy++ installs fine from ATN. S opens the folder input box, autocomplete on a few folder letters offers a folder list. TB is 78.6.0 as per distro. So a new install seems to work. Kali seems to be closely related to Ubuntu and Debian.

Other than that, I cannot really help with problems on Linux.

Klaus

**Comment by lingfish** [comment]
Sorry for the delays.  Yeah, I don't get this.  Here's what I see:

![image](https://user-images.githubusercontent.com/1295960/106695952-c9cbba00-662f-11eb-872c-067ff036ddd6.png)

![image](https://user-images.githubusercontent.com/1295960/106695945-c33d4280-662f-11eb-8ee5-8f1995393037.png)

**Comment by opto** [comment]
maybe reinstall? or install from TB website?
Ubuntu, Kali, Fedora, Suse is reported to be ok by others

**Comment by lingfish** [comment]
Very, very odd.  I went through various logs, and the dev console, and couldn't see why it was making the decision it was.  Manually downloaded/installed, seems to be working fine.

**Comment by opto** [comment]
see ->Manually downloaded/installed, seems to be working fine.
