### ISSUE TITLE
New rule dialog box  GUI problem in TB >= 85

### ISSUE THREAD

**Issue by maherma-adg** [opto/nostalgy-xpi#86]
In the new rule dialog box all fields is showed in a straigth line, creating a very wide dialog and making very hard to add new rules because you can't reach the add button because it's out of screen.

OS: Catalina 10.15.7
TB version: 85.0b3 & 86.0b1
Nostalgy++ versions: 2.2.4 & 2.2.5

![Captura de pantalla 2021-02-05 a las 19 31 07](https://user-images.githubusercontent.com/6205177/107074418-fd057900-67e8-11eb-8a5e-7ccde1f6a4bc.png)

EDIT: The Key configuration dialog suffer form same problem but the horizontal  scroll bar saved the day.

**Comment by opto** [comment]
workaround se #83

**Comment by maherma-adg** [comment]
I  toggled the mentioned option after upgrade to TB 86.0b1 in order to get addon back to work, but this not solve the dialog size problem.

**Comment by opto** [comment]
please try 2.2.6 to see whether it works for you as well. (under releases)

Klaus

**Comment by maherma-adg** [comment]
Add & Edit dialog box on Rules tab are fixed.

Keys tab still show a long horizontal line with all options.

Thanks for the fix.

**Comment by maherma-adg** [comment]
Side Note:  The Preferences dialog box is a little small for rules page content and when open, accept and usage buttons on the bottom of dialog are hidden.
Resize the dialog show these buttons but when closed and open again the size is not kept.

**Comment by opto** [comment]
sometime soon, this will go into the new options tab and will be 
redesigned ....


Due to replacement of listbox by richlistbox (not having columns), this 
dialog looks really bad .


Am 17.02.2021 um 22:44 schrieb maherma-adg:
