### ISSUE TITLE
keybinding Shift+S not working in German Thunderbird

### ISSUE THREAD

**Issue by moaltmann** [opto/nostalgy-xpi#87]
Thunderbird in German will not accept Shift+S (even if in preferences it is possible to set this key combination). 
Status bar of Thunderbird shows 
![[+Shift: => xxx@xxxxxxxx.xxx/xxxxxx]](https://user-images.githubusercontent.com/78542525/107285710-d7ce7000-6a5f-11eb-8eb5-59102515fc6c.jpg)

**Work-around** 
Changing interface to English and restarting Thunderbird results in Shift+S working as expected.

**Version Info**
TB 78.7.1 (64-bit) on Windows 10
Nostalgy 2.2.4

**Comment by opto** [comment]
Interesting. 78.7.0 configuration in German is working here, using it daily.
Do other letters work? Maybe reinstall?

Tomorrow, I will try 78.7.1

Klaus

**Comment by opto** [comment]
there maybe a conflict with S = set star. In 78, it is wired differently into TB.

**Comment by Olifair** [comment]
I have also 78.7.1 (32-bit) on windows 10 and SHIFT-S is working as expected. I hope updating to .1 will not break it ;-)

**Comment by opto** [comment]
I just tested 78.1.1 on win 10 home/64 bit  in TB 32bit, and S/shift S is working.

In one case, I think I remember I had to explicitly (re-) set S in the options dialog. Maybe that would help?
Maybe redownload/reinstall?

Klaus

**Comment by opto** [comment]
Please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.1 for TB 78 - TB 91
