### ISSUE TITLE
wide path makes window widen

### ISSUE THREAD

**Issue by mcswell** [opto/nostalgy-xpi#88]
If I'm saving to a long path (either because the target folder is deeply nested, or because one or more of the folder names in the path to that folder is long), it forces the entire Thunderbird window to get wider.  This is a problem because the way my monitors are set up, Thunderbird paints itself over other applications' windows.  I would prefer that the TBird window not expand just because the "save to" path is wide.

Not sure this can be fixed; maybe it's an inherent part of Thunderbird's status bar that if s.t. takes up too much room, TBird enlarges.  If that's the case, then I guess one solution would be to put the dialog into a menu, as per issue #73.  Or maybe there's a way to put the save-to dialog further left in the status bar (#75), so it has room to expand?

**Comment by matthewn** [comment]
Also experiencing this. Nostalgy is nearly doubling the width of my window the moment I activate it, kinda making the addon unusable in its current form. This is on Linux, in case that matters, with TB 78.7.1.

**Comment by sphh** [comment]
@mcswell: Is this the same as #37?

**Comment by mcswell** [comment]
Oops, it is; sorry I didn't see that before.  So I'm closing my 'issue' with this comment.

**Comment by mcswell** [comment]
That said, I am confused: I appear to have v2.2.4, and #37 says it was fixed in 2.2.3, and issue 37 is marked as resolved.  But it's still happening to me, so I think it is NOT resolved.  Should I reopen this (88) or that (37)?

**Comment by sphh** [comment]
How I interpret it: The issue #37 has the tag `resolved` but is still open, hence for me it is still open.

The solution I use is to limit the width of the entry box, as mentioned in https://github.com/opto/nostalgy-xpi/issues/37#issuecomment-727855179 and https://github.com/opto/nostalgy-xpi/issues/38#issuecomment-735444327 (look also at https://github.com/opto/nostalgy-xpi/issues/38#issuecomment-736854049, because this option is not (yet) available in the option page).

**Comment by mcswell** [comment]
Thanks--I confirm that the setting ( TB options: tools->settings. At the bottom of the General tab, open about:config.
Adjust extensions.nostalgy.FolderBoxChars) fixes the problem.  Now, if I could omit the button that says "N++ Help" on the status bar, I'd have more room, and could make the folder box longer so as to display more of the text.  But your suggestion is good, thank you!

**Comment by sphh** [comment]
See #91.
