### ISSUE TITLE
[Request] implement releases in main nostalgy repo

### ISSUE THREAD

**Issue by PresGas** [opto/nostalgy-xpi#9]
Request to implement putting nostalgy-xpi releases into the forked project (https://github.com/opto/nostalgy) or create a new project separated from upstream in order to implement. @alainfrisch seems to have definitely relinquished ownership of further development.

cc-ing @aeromorrison @mdonz

**Comment by opto** [comment]
yes, I will do so ca. this weekend, also make sure that it will be available on addons.thunderbird.net.

Klaus

**Comment by PresGas** [comment]
@opto we really appreciate your efforts in this and I hope my ticket didn't sound nagging. It was my attempt at contributing. Thank you so very much!

**Comment by opto** [comment]
this is now the official repo for Nostalgy++
