### ISSUE TITLE
v2.2.6 prevents command-W use to close a message window

### ISSUE THREAD

**Issue by PointInSpace2** [opto/nostalgy-xpi#90]
v2.2.6 prevents command-W use to close a message window.  Reverting to 2.2.4 fixed it.

**Comment by neufeind** [comment]
similar issue with other hotkeys, like esc to close the message-window, ctrl-u to view the source of a message or also various hotkeys in the message-list. While running Thunderbird it was sufficient to disable and reenable Nostalgy. Possibly a problem how/when hotkeys are registered or so?

**Comment by ziomau10** [comment]
Also Ctrl-A is not working here. Reverting to 2.2.4 fixes it.

**Comment by opto** [comment]
you can set the shortcut letters in the settings: tools->Nostalgy++. Does that help?

Klaus
