### ISSUE TITLE
TB 87.0beta: Not folder found when search folder to move to

### ISSUE THREAD

**Issue by maherma-adg** [opto/nostalgy-xpi#92]
After update to TB 87.0beta I can move-to/goto folders because when I write on input text the only things founds are labels, no folders are found.

**Comment by opto** [comment]
thanks. versions > 78 are still im preparation.

**Comment by opto** [comment]
Please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.1 for TB 78 - TB 91
