### ISSUE TITLE
Unable to add keyboard shortcut.

### ISSUE THREAD

**Issue by RParr** [opto/nostalgy-xpi#94]
Kubuntu 20.04, Thunderbird 78.7.1, Nostalgy++ 2.2.4

Finally, from issue 63, and others discovered how to get to Nostalgy++ preferences.

However, once there, Keys tab, I am unable to add a keyboard shortcut.

Nothing I do seems to populate the dialog box.

Is this broken or is there a new trick not described in the help?

**Comment by brianharvey** [comment]
I can add two, but can't add a third.  Nostalgy++ 2.2.4, TB 78.8.1, MacOS 10.13.4

**Comment by ThierryArx** [comment]
Hi,

Same issue than RParr, but with :

- Windows 10 Enterprise 1809
- Thunderbird 78.8.1
- Nostalgy++ 2.2.4

Issue description: when creating an entry n "Keys", neither auto-completion for directory selection works, nor the Create button (no action at all on click).

Thanks

**Comment by opto** [comment]
I need to do some work to get all running for 87 (yes, new TB changes due to multitasking) and will leave this to be tested/resolved then (sometime soon)).

KLaus

**Comment by jaysmithgit** [comment]
Same problem as original poster.

Kubuntu 20.04, Thunderbird 78.7.1, Nostalgy++ 2.2.4

On same platform as original poster. We installed new computers and new Kubuntu, but had delayed migrating from very old TB to modern TB, originally because of Nostalgy did not work at all on newer TB versions until opto made Nostalgy++, but then delayed because Nostalgy++ still does not have some of the basic/previous capabilities as the old Nostalgy.

I hope that you will be able to find the time to make it work.  I will be *very* happy to donate generously -- you can hold me to that -- when it works at least as well as old Nostalgy.

**Comment by opto** [comment]
autocomplete now works for rule creation and for keys in version 2.3, upload in the next days.

**Comment by ThierryArx** [comment]
Very good news, well done \o/

Thanks a lot.

**Comment by ThierryArx** [comment]
Very good news, well done \o/

Thanks a lot.

**Comment by ThierryArx** [comment]
Hello opto,

I have just upgraded to 2.3 but unfortunately it doesn't work as exepected regarding auto-completion for key creation.
When typing in the path field, auto-completion does happen but with tags (like this: ":<TAG>",  beginning with ":") defined in Thunderbird but not with mailbox path.
Strange...

Thank you in advance for your feeling about that.

*** With Thunderbird 78.11.0 (32 bits)

**Comment by ThierryArx** [comment]
Sorry... specific char didn't appear in my previous comment:

Hello opto,

I have just upgraded to 2.3 but unfortunately it doesn't work as exepected regarding auto-completion for key creation.
When typing in the path field, auto-completion does happen but with tags (like this: ":TAG", beginning with ":") defined in Thunderbird but not with mailbox path.
Strange...

Thank you in advance for your feeling about that.

*** With Thunderbird 78.11.0 (32 bits)

**Comment by ThierryArx** [comment]
Hello,

I have read again the user guide.
So, my observation above is OK with auto-completion regarding Tags : new feature OK.
But, I do confirm, folders are not shown through auto-completion.

Thanks.

**Comment by opto** [comment]
I am not sure which window you mean.

If I go to options, open the tab called keys, at the bottom, I can define custom keys. Is that what you mean?

There is a go  save copy save+go. Next to it is a folder box. If I enter po, I get all folders having Posteingang (= German inbox) in it.

If you do not: which operating system, TB version? This is not yet fully tested higher than 78.

Klaus

**Comment by opto** [comment]
strange.
It works on my test TB: an empty TB, just installing Nostalgy.
It does work on my production TB with other addons, if I manually deinstall and then install 2.3.2 from here:
https://github.com/opto/nostalgy-xpi/releases/tag/v2.3.2
maybe you can test.

**Comment by ThierryArx** [comment]
Hi Opto,
Thank you for this.Before trying that can you please tell me if uninstalling Nostalgy manually will delete my keys configuration?If so, it may be a challenge for me as I might no be able to recreate them if the new relase still doesn't work...
Moreover I coul see on github that we are now at releace 2.3.8: should I install the latest release or try the one you mentionnes (2.3.2)?
Thank you.
BR,Thierry

    Le mercredi 16 juin 2021 à 11:47:27 UTC+2, opto ***@***.***> a écrit :  
 
 


strange.
It works on my test TB: an empty TB, just installing Nostalgy.
It does work on my production TB with other addons, if I manually deinstall and then install 2.3.2 from here:
https://github.com/opto/nostalgy-xpi/releases/tag/v2.3.2
maybe you can test.

**Comment by ThierryArx** [comment]
Opto,
Just try to deactivate all extensions on my TB (just in case), uninstall Nostalgy and reinsall Nostalgy 2.3.8: same result :-(


    Le lundi 21 juin 2021 à 09:40:32 UTC+2, Thierry ARNOUX ***@***.***> a écrit :  
 
  Hi Opto,
Thank you for this.Before trying that can you please tell me if uninstalling Nostalgy manually will delete my keys configuration?If so, it may be a challenge for me as I might no be able to recreate them if the new relase still doesn't work...
Moreover I coul see on github that we are now at releace 2.3.8: should I install the latest release or try the one you mentionnes (2.3.2)?
Thank you.
BR,Thierry

    Le mercredi 16 juin 2021 à 11:47:27 UTC+2, opto ***@***.***> a écrit :  
 
 


strange.
It works on my test TB: an empty TB, just installing Nostalgy.
It does work on my production TB with other addons, if I manually deinstall and then install 2.3.2 from here:
https://github.com/opto/nostalgy-xpi/releases/tag/v2.3.2
maybe you can test.

**Comment by opto** [comment]
Please try https://github.com/opto/nostalgy-xpi/releases/tag/v3.0.1 for TB 78 - TB 91

**Comment by brianharvey** [comment]
I downloaded and installed your new version and now not only doesn't bcc work, neither does keyboard shortcuts for saving to a particular folder.  :(  Thunderbird 78.12.0, MacOS 10.13.4.  64 bit.

**Comment by ThierryArx** [comment]
Hello opto,

Thank you for your work on this new release.
New design is quite better!

However it still doesn't work for me :-(

Regarding key shortcuts issue, same status for me: only TAGS are listed while Aauto-completion.
Moreover I have another issue: path with accents (é, è... sorry I am French :-) ) are not recognized anymore --> locale issue I guess.
a
Thanks.

My current configuration:
Windows 10 1909
TB 78.12.0 (32 bits)

**Comment by ThierryArx** [comment]
Hello opto,
Just installed release 3.0.7 and now all issues about shortcuts in the Keys tab seem fixed for me!
Thanks a lot for this great job.
ThierryArx

**Comment by ThierryArx** [comment]
Hmmm... it seems I went too quickly in my conclusion.

I have now another issue: sometimes - but I cannot identify if it is due to a specific action - I cannot change of directory anymore (with mouse or key shortcut).
To solve the point - temporarily - I have to restart TB.

Thanks!

My current configuration:
Windows 10 1909
TB 78.13.0 (32 bits)

**Comment by opto** [comment]
yes, I had that once, but it came never again. Anything to reproduce it would be good.

**Comment by ThierryArx** [comment]
I found the way to reproduce this new problem: please see issue #127 (Impossible to go to another folder after displaying the context menu of a folder in the folder pane.)
